from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
JAVA=ROOT/'app/src/main/java/com/musicroad/ai'

def rep(path, old, new, label):
    s=path.read_text()
    if old not in s:
        raise SystemExit(f'v4.6 patch failed: {label} not found in {path.name}')
    path.write_text(s.replace(old,new,1))

def nav():
    p=JAVA/'NavigationService.java'
    rep(p,'import android.os.Looper;','import android.os.Looper;\nimport android.os.VibrationEffect;\nimport android.os.Vibrator;','nav imports')
    rep(p,'    private static final String PREFS="musicroad_navigation_v1";\n    private static final String CH_TRIP="musicroad_trip";\n    private static final String CH_ALERT="musicroad_road_alert";',
          '    private static final String PREFS="musicroad_navigation_v1";\n    public static final String ALERT_PREFS="musicroad_alert_prefs_v2";\n    private static final String CH_TRIP="musicroad_trip";\n    private static final String CH_ALERT="musicroad_road_alert_v2";','nav prefs constants')
    rep(p,'NotificationChannel alert=new NotificationChannel(CH_ALERT,"Alertas de fiscalização",NotificationManager.IMPORTANCE_HIGH);alert.setDescription("Avisos temporários de fiscalização e segurança viária");alert.setSound(null,null);alert.enableVibration(true);alert.setVibrationPattern(new long[]{0,120,80,120});',
          'NotificationChannel alert=new NotificationChannel(CH_ALERT,"Alertas MusicRoad",NotificationManager.IMPORTANCE_HIGH);alert.setDescription("Alertas temporários configuráveis de fiscalização, segurança e navegação");alert.setSound(null,null);alert.enableVibration(false);','nav alert channel')
    old='    private void showTransient(String title,String text,long durationMs){Notification.Builder b=builder(CH_ALERT).setSmallIcon(R.drawable.ic_notification).setContentTitle(title).setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setContentIntent(openAppIntent()).setAutoCancel(true).setCategory(Notification.CATEGORY_NAVIGATION).setOnlyAlertOnce(false);if(Build.VERSION.SDK_INT>=26)b.setTimeoutAfter(durationMs);else b.setPriority(Notification.PRIORITY_HIGH);notificationManager.notify(NOTIF_ALERT,b.build());handler.removeCallbacksAndMessages("road-alert");handler.postAtTime(()->notificationManager.cancel(NOTIF_ALERT),"road-alert",System.currentTimeMillis()+durationMs);}'
    new='''    private SharedPreferences alertPrefs(){return getSharedPreferences(ALERT_PREFS,MODE_PRIVATE);}\n    private boolean pref(String key,boolean def){return alertPrefs().getBoolean(key,def);}\n    private boolean milestoneEnabled(int meters){return pref("m"+meters,true);}\n    private boolean kindEnabled(Hazard h){return h!=null&&pref(h.kind(),true);}\n    private void vibrateAlert(){if(!pref("vibrate",true))return;try{Vibrator v=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(v==null||!v.hasVibrator())return;if(Build.VERSION.SDK_INT>=26)v.vibrate(VibrationEffect.createWaveform(new long[]{0,110,70,110},-1));else v.vibrate(new long[]{0,110,70,110},-1);}catch(Exception ignored){}}\n    private void showTransient(String title,String text,long durationMs){vibrateAlert();if(!pref("system",true))return;Notification.Builder b=builder(CH_ALERT).setSmallIcon(R.drawable.ic_notification).setContentTitle(title).setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setContentIntent(openAppIntent()).setAutoCancel(true).setCategory(Notification.CATEGORY_NAVIGATION).setOnlyAlertOnce(false);if(Build.VERSION.SDK_INT>=26)b.setTimeoutAfter(durationMs);else b.setPriority(Notification.PRIORITY_HIGH);notificationManager.notify(NOTIF_ALERT,b.build());handler.removeCallbacksAndMessages("road-alert");handler.postAtTime(()->notificationManager.cancel(NOTIF_ALERT),"road-alert",System.currentTimeMillis()+durationMs);}'''
    rep(p,old,new,'nav showTransient')
    rep(p,'        if(next!=null){if("bump".equals(next.kind()))handleBumpHazard(next,progress);else handleHazard(next,progress);}',
          '        if(next!=null&&kindEnabled(next)){if("bump".equals(next.kind()))handleBumpHazard(next,progress);else handleHazard(next,progress);}','nav kind gate')
    rep(p,'    private void handleHazard(Hazard h,double progress){\n        double distance=Math.max(0,h.routeM-progress);String key=h.key;int milestone=milestoneFor(distance);\n        if(milestone>0){',
          '    private void handleHazard(Hazard h,double progress){\n        if(!kindEnabled(h))return;double distance=Math.max(0,h.routeM-progress);String key=h.key;int milestone=milestoneFor(distance);\n        if(milestone>0&&milestoneEnabled(milestone)){','nav hazard prefs')
    rep(p,'        if(distance<=22&&!warnedNow.contains(key)){','        if(pref("front",true)&&distance<=22&&!warnedNow.contains(key)){','nav front')
    rep(p,'        if(milestone>=100){','        if(milestone>=100&&milestoneEnabled(milestone)){','nav bump sequence distance')
    rep(p,'        if(distance<=50&&distance>22){','        if(milestoneEnabled(50)&&distance<=50&&distance>22){','nav bump50')
    rep(p,'        if(distance<=22&&!warnedNow.contains(h.key)){','        if(pref("front",true)&&distance<=22&&!warnedNow.contains(h.key)){','nav bump front')
    rep(p,'    private void handleManeuver(double progress){\n        Maneuver m=nextManeuver(progress);','    private void handleManeuver(double progress){\n        if(!pref("maneuvers",true))return;Maneuver m=nextManeuver(progress);','nav maneuvers')
    rep(p,'    private void handleSpeeding(long kmh,int limit){long now=System.currentTimeMillis();','    private void handleSpeeding(long kmh,int limit){if(!pref("speeding",true))return;long now=System.currentTimeMillis();','nav speeding')
    rep(p,'    private void speak(String text){try{Intent i=PlaybackService.intentAction(this,PlaybackService.ACTION_SPEAK);','    private void speak(String text){if(!pref("voice",true))return;try{Intent i=PlaybackService.intentAction(this,PlaybackService.ACTION_SPEAK);','nav voice')

def playback():
    p=JAVA/'PlaybackService.java'
    rep(p,'import android.content.Intent;','import android.content.Intent;\nimport android.content.SharedPreferences;','playback prefs import')
    rep(p,'import android.speech.tts.UtteranceProgressListener;','import android.speech.tts.UtteranceProgressListener;\nimport android.speech.tts.Voice;','playback voice import')
    rep(p,'import java.util.Map;','import java.util.Map;\nimport java.util.Set;','playback set import')
    rep(p,'    public static final String ACTION_SPEAK="com.musicroad.ai.SPEAK";','    public static final String ACTION_SPEAK="com.musicroad.ai.SPEAK";\n    public static final String ACTION_TTS_CONFIG="com.musicroad.ai.TTS_CONFIG";','playback config action')
    rep(p,'    public static final String EXTRA_TEXT="text";','    public static final String EXTRA_TEXT="text";\n    public static final String EXTRA_FORCE="force";','playback force')
    rep(p,'        else if(ACTION_SPEAK.equals(a)) speakAlert(intent.getStringExtra(EXTRA_TEXT));','        else if(ACTION_TTS_CONFIG.equals(a)) applyTtsPreferences();\n        else if(ACTION_SPEAK.equals(a)) speakAlert(intent.getStringExtra(EXTRA_TEXT),intent.getBooleanExtra(EXTRA_FORCE,false));','playback action handling')
    old='''    private void createTts(){\n        tts=new TextToSpeech(getApplicationContext(),status->{\n            ttsReady=status==TextToSpeech.SUCCESS;\n            if(ttsReady){\n                tts.setLanguage(new Locale("pt","BR"));\n                tts.setSpeechRate(.98f);\n                tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){\n                    @Override public void onStart(String utteranceId){ }\n                    @Override public void onDone(String utteranceId){handler.post(PlaybackService.this::restoreAfterAlert);}\n                    @Override public void onError(String utteranceId){handler.post(PlaybackService.this::restoreAfterAlert);}\n                });\n            }\n        });\n    }\n\n    private void speakAlert(String text){\n        if(text==null||text.trim().isEmpty())return;\n        alertDuck=.24f;applyVolume();'''
    new='''    private SharedPreferences alertPrefs(){return getSharedPreferences(NavigationService.ALERT_PREFS,MODE_PRIVATE);}\n    private void createTts(){\n        tts=new TextToSpeech(getApplicationContext(),status->{\n            ttsReady=status==TextToSpeech.SUCCESS;\n            if(ttsReady){applyTtsPreferences();tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){\n                @Override public void onStart(String utteranceId){ }\n                @Override public void onDone(String utteranceId){handler.post(PlaybackService.this::restoreAfterAlert);}\n                @Override public void onError(String utteranceId){handler.post(PlaybackService.this::restoreAfterAlert);}\n            });}\n        });\n    }\n    private void applyTtsPreferences(){if(!ttsReady||tts==null)return;SharedPreferences p=alertPrefs();try{tts.setLanguage(new Locale("pt","BR"));String name=p.getString("voiceName","");if(name!=null&&!name.isEmpty()){Set<Voice> voices=tts.getVoices();if(voices!=null)for(Voice v:voices)if(name.equals(v.getName())){tts.setVoice(v);break;}}tts.setSpeechRate(Math.max(.6f,Math.min(1.6f,p.getFloat("voiceRate",1f))));tts.setPitch(Math.max(.6f,Math.min(1.5f,p.getFloat("voicePitch",1f))));}catch(Exception ignored){}}\n\n    private void speakAlert(String text,boolean force){\n        if(text==null||text.trim().isEmpty())return;if(!force&&!alertPrefs().getBoolean("voice",true))return;applyTtsPreferences();\n        alertDuck=.24f;applyVolume();'''
    rep(p,old,new,'playback tts block')
    rep(p,'headers.put("User-Agent","MusicRoadAndroid/3.0");','headers.put("User-Agent","MusicRoadAndroid/"+BuildConfig.VERSION_NAME);','playback UA')

def bridge():
    p=JAVA/'NativeBridge.java'
    rep(p,'import android.content.pm.PackageManager;','import android.content.pm.PackageManager;\nimport android.content.pm.ResolveInfo;','bridge resolveinfo')
    rep(p,'import android.os.Environment;','import android.os.Environment;\nimport android.speech.tts.TextToSpeech;\nimport android.speech.tts.Voice;','bridge tts imports')
    rep(p,'import java.util.Locale;','import java.util.ArrayList;\nimport java.util.Comparator;\nimport java.util.List;\nimport java.util.Locale;\nimport java.util.Set;','bridge util imports')
    rep(p,'    private static final String DOWNLOAD_PREFS="musicroad_offline_downloads_v1";','    private static final String DOWNLOAD_PREFS="musicroad_offline_downloads_v1";\n    private static final String[] ALERT_BOOLEAN_KEYS={"voice","visual","system","vibrate","maneuvers","speeding","m300","m200","m100","m50","front","radar","portable","video","signal","bump"};','bridge keys')
    rep(p,'    private SharedPreferences downloadPrefs(){return activity.getSharedPreferences(DOWNLOAD_PREFS,Context.MODE_PRIVATE);}\n    private static String pkey(String prefix,String key){return prefix+(key==null?"":key);}',
          '''    private SharedPreferences downloadPrefs(){return activity.getSharedPreferences(DOWNLOAD_PREFS,Context.MODE_PRIVATE);}\n    private SharedPreferences alertPrefs(){return activity.getSharedPreferences(NavigationService.ALERT_PREFS,Context.MODE_PRIVATE);}\n    private static String pkey(String prefix,String key){return prefix+(key==null?"":key);}\n\n    @JavascriptInterface public void setAlertPreferences(String json){try{JSONObject o=new JSONObject(json==null?"{}":json);SharedPreferences.Editor e=alertPrefs().edit();for(String key:ALERT_BOOLEAN_KEYS)if(o.has(key))e.putBoolean(key,o.optBoolean(key,true));if(o.has("voiceName"))e.putString("voiceName",o.optString("voiceName",""));if(o.has("voiceRate"))e.putFloat("voiceRate",(float)Math.max(.6,Math.min(1.6,o.optDouble("voiceRate",1))));if(o.has("voicePitch"))e.putFloat("voicePitch",(float)Math.max(.6,Math.min(1.5,o.optDouble("voicePitch",1))));e.apply();activity.startService(PlaybackService.intentAction(activity,PlaybackService.ACTION_TTS_CONFIG));}catch(Exception ignored){}}\n    @JavascriptInterface public void setTtsPreferences(String voiceName,double rate,double pitch){alertPrefs().edit().putString("voiceName",voiceName==null?"":voiceName).putFloat("voiceRate",(float)Math.max(.6,Math.min(1.6,rate))).putFloat("voicePitch",(float)Math.max(.6,Math.min(1.5,pitch))).apply();activity.startService(PlaybackService.intentAction(activity,PlaybackService.ACTION_TTS_CONFIG));}\n    @JavascriptInterface public void testTtsVoice(String text){Intent i=PlaybackService.intentAction(activity,PlaybackService.ACTION_SPEAK);i.putExtra(PlaybackService.EXTRA_TEXT,text==null?"Olá. Esta é a voz do copiloto MusicRoad.":text);i.putExtra(PlaybackService.EXTRA_FORCE,true);activity.startService(i);}\n    @JavascriptInterface public void requestTtsVoices(){activity.runOnUiThread(()->{final TextToSpeech[] holder=new TextToSpeech[1];holder[0]=new TextToSpeech(activity.getApplicationContext(),status->{JSONArray out=new JSONArray();try{if(status==TextToSpeech.SUCCESS&&holder[0]!=null){Set<Voice> set=holder[0].getVoices();List<Voice> voices=new ArrayList<>();if(set!=null)for(Voice v:set){Locale loc=v.getLocale();if(loc!=null&&"pt".equalsIgnoreCase(loc.getLanguage()))voices.add(v);}voices.sort(Comparator.comparing((Voice v)->v.isNetworkConnectionRequired()).thenComparing(Voice::getName));for(Voice v:voices){JSONObject o=new JSONObject();o.put("name",v.getName());o.put("locale",v.getLocale()==null?"pt-BR":v.getLocale().toLanguageTag());o.put("network",v.isNetworkConnectionRequired());out.put(o);}}}catch(Exception ignored){}dispatchJs("document.dispatchEvent(new CustomEvent('mr:tts-voices',{detail:{voices:"+out.toString()+"}}));");try{if(holder[0]!=null)holder[0].shutdown();}catch(Exception ignored){}});});}''','bridge prefs methods')
    radio='''\n    private JSONObject findFmRadioApp(){JSONObject out=new JSONObject();try{PackageManager pm=activity.getPackageManager();Intent q=new Intent(Intent.ACTION_MAIN);q.addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo> apps=pm.queryIntentActivities(q,PackageManager.MATCH_DEFAULT_ONLY);ResolveInfo best=null;String labelBest="";for(ResolveInfo r:apps){String pkg=r.activityInfo==null?"":r.activityInfo.packageName;if(pkg.equals(activity.getPackageName()))continue;String label=String.valueOf(r.loadLabel(pm));String l=label.toLowerCase(Locale.ROOT),pk=pkg.toLowerCase(Locale.ROOT);boolean match=l.contains("rádio")||l.contains("radio")||l.equals("fm")||l.startsWith("fm ")||l.endsWith(" fm")||pk.contains("fmradio")||pk.contains("fm.radio")||pk.endsWith(".radio");if(match){best=r;labelBest=label;break;}}if(best!=null&&best.activityInfo!=null){out.put("available",true);out.put("label",labelBest);out.put("package",best.activityInfo.packageName);out.put("class",best.activityInfo.name);}else out.put("available",false);}catch(Exception e){try{out.put("available",false);}catch(Exception ignored){}}return out;}\n    @JavascriptInterface public String getFmRadioStatus(){return findFmRadioApp().toString();}\n    @JavascriptInterface public boolean openFmRadioApp(){JSONObject f=findFmRadioApp();if(!f.optBoolean("available",false))return false;try{String pkg=f.optString("package",""),cls=f.optString("class","");Intent launch=activity.getPackageManager().getLaunchIntentForPackage(pkg);if(launch==null&&!cls.isEmpty()){launch=new Intent(Intent.ACTION_MAIN);launch.addCategory(Intent.CATEGORY_LAUNCHER);launch.setClassName(pkg,cls);}if(launch==null)return false;launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);Intent finalLaunch=launch;activity.runOnUiThread(()->{try{activity.startActivity(finalLaunch);}catch(Exception e){Toast.makeText(activity,"Não foi possível abrir o rádio FM do aparelho.",Toast.LENGTH_SHORT).show();}});return true;}catch(Exception e){return false;}}\n'''
    rep(p,'\n    @JavascriptInterface public boolean startNavigation(',radio+'\n    @JavascriptInterface public boolean startNavigation(','bridge radio methods')

nav();playback();bridge()
print('MusicRoad Android v4.6 source patches applied')
