<?php
declare(strict_types=1);
require __DIR__ . '/api/bootstrap.php';
require_once __DIR__ . '/api/server_intelligent.php';
require_once __DIR__ . '/api/road_hazard_db.php';
ensure_default_users();
$admin=require_admin();
intelligent_server_ensure_schema();
road_hazard_ensure_tables();

function epca_e(mixed $v): string { return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); }
function epca_scalar(string $sql,array $params=[],mixed $default=0): mixed { try{$s=db()->prepare($sql);$s->execute($params);$v=$s->fetchColumn();return $v===false?$default:$v;}catch(Throwable $e){return $default;} }
function epca_rows(string $sql,array $params=[]): array { try{$s=db()->prepare($sql);$s->execute($params);return $s->fetchAll()?:[];}catch(Throwable $e){return [];} }
function epca_mask(string $token): string { $token=trim($token);return $token===''?'—':substr($token,0,5).'…'.substr($token,-4); }
function epca_map(float $lat,float $lon): string { return 'https://www.openstreetmap.org/?mlat='.rawurlencode((string)$lat).'&mlon='.rawurlencode((string)$lon).'#map=15/'.$lat.'/'.$lon; }
function epca_online(?string $value,int $seconds=900): bool { if(!$value)return false;$t=strtotime($value);return $t!==false&&time()-$t<=$seconds; }
function epca_event_label(string $type): string { return ['pothole'=>'BURACO','animal'=>'ANIMAL','accident'=>'ACIDENTE','construction'=>'OBRA','flooding'=>'ALAGAMENTO','traffic'=>'TRÂNSITO','object'=>'OBJETO'][$type]??strtoupper($type); }
function epca_status_class(string $s): string { $s=strtoupper($s);return in_array($s,['ATIVO','ACTIVE','CONFIRMADO','OK','LIVRE'],true)?'ok':(in_array($s,['PENDENTE','ATENÇÃO','WARN','MODERADO','LENTO'],true)?'warn':'bad'); }

$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='toggle_client'){
            $id=(int)($_POST['client_id']??0);$s=db()->prepare("UPDATE users SET status=CASE WHEN status='active' THEN 'inactive' ELSE 'active' END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND role='client'");$s->execute([$id]);audit_log('epc_admin.client_toggle',['client_id'=>$id]);$message='Status do usuário atualizado.';
        }elseif($action==='reset_password'){
            $id=(int)($_POST['client_id']??0);$password=(string)($_POST['new_password']??'');if(strlen($password)<6)throw new RuntimeException('A nova senha precisa ter pelo menos 6 caracteres.');$s=db()->prepare("UPDATE users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND role='client'");$s->execute([password_hash($password,PASSWORD_DEFAULT),$id]);audit_log('epc_admin.password_reset',['client_id'=>$id]);$message='Senha redefinida.';
        }elseif($action==='report_status'){
            $id=(int)($_POST['report_id']??0);$status=strtoupper((string)($_POST['status']??''));if(!intelligent_server_set_report_status($id,$status,(int)$admin['id']))throw new RuntimeException('Não foi possível atualizar esse relato.');$message='Relato atualizado para '.$status.'.';
        }elseif($action==='delete_live_event'){
            $id=(int)($_POST['event_id']??0);db()->beginTransaction();try{$s=db()->prepare('DELETE FROM road_live_votes WHERE event_id=?');$s->execute([$id]);if(schema_columns('road_live_confirmations')){$s=db()->prepare('DELETE FROM road_live_confirmations WHERE event_id=?');$s->execute([$id]);}$s=db()->prepare('DELETE FROM road_live_events WHERE id=?');$s->execute([$id]);db()->commit();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}audit_log('epc_admin.live_event_delete',['event_id'=>$id]);$message='Alerta comunitário removido.';
        }elseif($action==='delete_fuel'){
            $id=(int)($_POST['fuel_id']??0);$s=db()->prepare('DELETE FROM fuel_price_reports WHERE id=?');$s->execute([$id]);audit_log('epc_admin.fuel_delete',['fuel_id'=>$id]);$message='Preço de combustível removido.';
        }elseif($action==='close_convoy'){
            $id=(int)($_POST['convoy_id']??0);db()->beginTransaction();try{$s=db()->prepare('DELETE FROM estrada_convoy_members WHERE convoy_id=?');$s->execute([$id]);$s=db()->prepare('DELETE FROM estrada_convoys WHERE id=?');$s->execute([$id]);db()->commit();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}audit_log('epc_admin.convoy_close',['convoy_id'=>$id]);$message='Comboio encerrado.';
        }elseif($action==='housekeeping'){
            $r=intelligent_server_housekeeping(true);audit_log('epc_admin.housekeeping',['deleted'=>(int)($r['deleted']??0)]);$message='Manutenção executada. Registros expirados removidos: '.(int)($r['deleted']??0).'.';
        }elseif($action==='clear_weather'){
            $s=db()->prepare('DELETE FROM road_weather_cache');$s->execute();audit_log('epc_admin.weather_cache_clear',['deleted'=>$s->rowCount()]);$message='Cache meteorológico limpo.';
        }
    }catch(Throwable $e){$error=$e->getMessage()?:'Não foi possível concluir a ação.';}
}

$now=date('Y-m-d H:i:s');$onlineCut=date('Y-m-d H:i:s',time()-900);$fuelCut=date('Y-m-d H:i:s',time()-36*3600);
$health=server_health_snapshot(false);$reportStats=intelligent_server_report_stats();$contextStats=ep7_context_stats();
$metrics=[
 'clients'=>(int)epca_scalar("SELECT COUNT(*) FROM users WHERE role='client'"),
 'active_clients'=>(int)epca_scalar("SELECT COUNT(*) FROM users WHERE role='client' AND status='active'"),
 'online_devices'=>(int)epca_scalar('SELECT COUNT(*) FROM client_device_state WHERE last_seen_at>=?',[$onlineCut]),
 'live_events'=>(int)epca_scalar('SELECT COUNT(*) FROM road_live_events WHERE expires_at>?',[$now]),
 'traffic_samples'=>(int)epca_scalar('SELECT COUNT(*) FROM road_traffic_samples WHERE expires_at>?',[$now]),
 'weather_cache'=>(int)epca_scalar('SELECT COUNT(*) FROM road_weather_cache WHERE expires_at>?',[$now]),
 'fuel_reports'=>(int)epca_scalar('SELECT COUNT(*) FROM fuel_price_reports WHERE created_at>=?',[$fuelCut]),
 'hazards'=>(int)epca_scalar('SELECT COUNT(*) FROM road_hazards WHERE active=1'),
 'convoys'=>(int)epca_scalar('SELECT COUNT(*) FROM estrada_convoys WHERE expires_at>?',[$now]),
 'pending_reports'=>(int)($reportStats['pending']??0),
];
$clients=epca_rows("SELECT u.id,u.name,u.email,u.username,u.status,u.last_login_at,u.created_at,COUNT(d.id) devices,MAX(d.last_seen_at) last_device_seen FROM users u LEFT JOIN client_device_state d ON d.user_id=u.id WHERE u.role='client' GROUP BY u.id,u.name,u.email,u.username,u.status,u.last_login_at,u.created_at ORDER BY u.id DESC LIMIT 120");
$devices=epca_rows("SELECT d.*,u.name user_name,u.username FROM client_device_state d JOIN users u ON u.id=d.user_id ORDER BY d.last_seen_at DESC LIMIT 80");
$reports=epca_rows('SELECT id,user_id,type,latitude,longitude,speed_kmh,limit_kmh,note,source,status,created_at,reviewed_at FROM road_reports ORDER BY id DESC LIMIT 100');
$live=epca_rows('SELECT id,user_id,event_type,latitude,longitude,road,note,confirmations,dismissals,heading,speed_kmh,expires_at,created_at,last_feedback_at FROM road_live_events WHERE expires_at>? ORDER BY created_at DESC LIMIT 100',[$now]);
$traffic=epca_rows("SELECT cell_key,MAX(COALESCE(road,'')) road,ROUND(AVG(speed_kmh),1) avg_speed,ROUND(AVG(COALESCE(limit_kmh,0)),1) avg_limit,COUNT(*) samples,MAX(updated_at) updated_at FROM road_traffic_samples WHERE expires_at>? GROUP BY cell_key ORDER BY samples DESC,updated_at DESC LIMIT 60",[$now]);
$weather=epca_rows('SELECT cache_key,latitude,longitude,fetched_at,expires_at FROM road_weather_cache ORDER BY fetched_at DESC LIMIT 50');
$fuel=epca_rows('SELECT id,user_id,station,fuel,price,latitude,longitude,reported_at,created_at FROM fuel_price_reports WHERE created_at>=? ORDER BY created_at DESC LIMIT 100',[$fuelCut]);
$hazardStats=road_hazard_stats();$hazardSync=road_hazard_sync_status();
$convoys=epca_rows("SELECT c.id,c.code,c.title,c.owner_user_id,c.created_at,c.expires_at,COUNT(m.device_token) members,MAX(m.last_seen) last_seen FROM estrada_convoys c LEFT JOIN estrada_convoy_members m ON m.convoy_id=c.id WHERE c.expires_at>? GROUP BY c.id,c.code,c.title,c.owner_user_id,c.created_at,c.expires_at ORDER BY c.created_at DESC LIMIT 50",[$now]);
$logs=epca_rows('SELECT action,payload,ip,created_at FROM audit_logs ORDER BY id DESC LIMIT 80');
$quota=(float)($health['quota_percent']??0);$quotaLevel=(string)($health['quota_level']??'ok');$csrf=csrf_token();
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#080808"><title>EPC · Painel Administrativo</title><link rel="stylesheet" href="assets/css/admin-epc.css?v=1.0.0"></head><body>
<div class="epc-shell"><aside class="epc-sidebar"><div class="epc-brand"><div class="epc-star">★</div><div><strong>ESTRADA PLAY</strong><small>COMUNISTA · ADMIN</small></div></div><nav class="epc-nav">
<a class="active" href="#visao"><span class="icon">◈</span>Visão geral</a><a href="#usuarios"><span class="icon">●</span>Usuários</a><a href="#estrada-viva"><span class="icon">▲</span>Estrada Viva</a><a href="#trafego-clima"><span class="icon">≋</span>Trânsito & Clima</a><a href="#combustivel"><span class="icon">◆</span>Combustível</a><a href="#radares"><span class="icon">◎</span>Radares</a><a href="#comboios"><span class="icon">▶</span>Comboios</a><a href="#servidor"><span class="icon">▣</span>Servidor</a><a href="#auditoria"><span class="icon">⌁</span>Auditoria</a></nav><div class="epc-sidebar-bottom">Administrador<br><strong><?=epca_e($admin['name']??$admin['username'])?></strong><a href="admin.php">Painel legado</a><a href="admin_server.php">Central do servidor</a><a href="logout.php">Sair</a></div></aside>
<main class="epc-main"><header class="epc-topbar"><div><p class="epc-kicker">EPC · COMANDO CENTRAL</p><h1>Painel Administrativo</h1><p>Mesmo banco de dados do Estrada Play · Server <?=epca_e(ESTRADAPLAY_SERVER_INTELLIGENT_VERSION)?> · <span data-live-stamp>dados atuais</span></p></div><div class="epc-actions"><a class="epc-btn gold" href="admin_radares.php">Central de radares</a><a class="epc-btn" href="admin_server.php">Servidor</a><a class="epc-btn danger" href="logout.php">Sair</a></div></header>
<?php if($message):?><div class="epc-alert ok"><?=epca_e($message)?></div><?php endif;?><?php if($error):?><div class="epc-alert bad"><?=epca_e($error)?></div><?php endif;?>
<section id="visao"><div class="epc-grid"><article class="epc-card gold"><span class="label">Usuários ativos</span><div class="metric" data-metric="active_clients"><?=$metrics['active_clients']?></div><div class="sub">de <span data-metric="clients"><?=$metrics['clients']?></span> contas</div></article><article class="epc-card"><span class="label">Aparelhos online</span><div class="metric" data-metric="online_devices"><?=$metrics['online_devices']?></div><div class="sub">atividade nos últimos 15 min</div></article><article class="epc-card"><span class="label">Estrada Viva agora</span><div class="metric" data-metric="live_events"><?=$metrics['live_events']?></div><div class="sub">alertas ainda válidos</div></article><article class="epc-card cyan"><span class="label">Trânsito colaborativo</span><div class="metric" data-metric="traffic_samples"><?=$metrics['traffic_samples']?></div><div class="sub">amostras efêmeras ativas</div></article><article class="epc-card"><span class="label">Relatos pendentes</span><div class="metric" data-metric="pending_reports"><?=$metrics['pending_reports']?></div><div class="sub">aguardando moderação</div></article><article class="epc-card gold"><span class="label">Preços recentes</span><div class="metric" data-metric="fuel_reports"><?=$metrics['fuel_reports']?></div><div class="sub">combustível · 36 horas</div></article><article class="epc-card"><span class="label">Base rodoviária</span><div class="metric" data-metric="hazards"><?=$metrics['hazards']?></div><div class="sub">pontos ativos</div></article><article class="epc-card cyan"><span class="label">Comboios ativos</span><div class="metric" data-metric="convoys"><?=$metrics['convoys']?></div><div class="sub">grupos ainda válidos</div></article></div>
<div class="epc-section"><div class="epc-section-head"><div><h2>Estado operacional</h2><p>Resumo do servidor metadata-only e das funções de estrada.</p></div></div><div class="epc-health"><div class="epc-health-main"><div class="epc-health-status"><div><span class="epc-dot <?=$quotaLevel==='ok'?'':($quotaLevel==='warning'?'warn':'bad')?>"></span><strong><?=epca_e($health['quota_label']??strtoupper($quotaLevel))?></strong><div class="epc-muted" style="margin-top:5px">Uso administrado <?=epca_e($health['managed_h']??'0 B')?> / <?=epca_e($health['quota_h']??'500 MB')?></div></div><strong><?=number_format($quota,1,',','.')?>%</strong></div><div class="epc-progress"><span data-quota-bar style="width:<?=min(100,max(0,$quota))?>%"></span></div></div><div class="epc-mini-grid"><div class="epc-mini"><strong data-metric="weather_cache"><?=$metrics['weather_cache']?></strong><span>pontos de clima em cache</span></div><div class="epc-mini"><strong><?=epca_e($health['db_h']??'0 B')?></strong><span>banco de dados</span></div><div class="epc-mini"><strong><?=epca_e($health['disk_free_h']??'—')?></strong><span>espaço livre no host</span></div><div class="epc-mini"><strong><?=count($hazardSync)?></strong><span>UFs com estado de sincronização</span></div></div></div></div></section>

<section id="usuarios" class="epc-section"><div class="epc-section-head"><div><h2>Usuários e aparelhos</h2><p>As mesmas contas usadas pelo aplicativo. Nenhum cadastro é duplicado.</p></div><input class="epc-input" data-user-filter placeholder="Filtrar usuário"></div><div class="epc-table-wrap"><table class="epc-table"><thead><tr><th>Cliente</th><th>Status</th><th>Dispositivos</th><th>Última atividade</th><th>Ações</th></tr></thead><tbody><?php if(!$clients):?><tr><td class="epc-empty" colspan="5">Nenhum cliente cadastrado.</td></tr><?php endif;?><?php foreach($clients as $c):$online=epca_online($c['last_device_seen']??null);?><tr data-user-row><td><strong><?=epca_e($c['name'])?></strong><br><span class="epc-muted"><?=epca_e($c['username'])?> · <?=epca_e($c['email'])?></span></td><td><span class="epc-badge <?=($c['status']==='active')?'ok':'bad'?>"><?=($c['status']==='active')?'ATIVO':'DESATIVADO'?></span> <?php if($online):?><span class="epc-badge cyan">ONLINE</span><?php endif;?></td><td><?=intval($c['devices'])?></td><td><?=epca_e($c['last_device_seen']?:($c['last_login_at']?:'Nunca'))?></td><td><div class="epc-inline"><form method="post"><input type="hidden" name="csrf" value="<?=epca_e($csrf)?>"><input type="hidden" name="action" value="toggle_client"><input type="hidden" name="client_id" value="<?=intval($c['id'])?>"><button class="epc-btn small" type="submit"><?=($c['status']==='active')?'Desativar':'Ativar'?></button></form><form method="post" class="epc-inline"><input type="hidden" name="csrf" value="<?=epca_e($csrf)?>"><input type="hidden" name="action" value="reset_password"><input type="hidden" name="client_id" value="<?=intval($c['id'])?>"><input class="epc-input compact" name="new_password" type="password" minlength="6" placeholder="Nova senha" required><button class="epc-btn small gold" type="submit">Redefinir</button></form></div></td></tr><?php endforeach;?></tbody></table></div>
<div class="epc-section-head" style="margin-top:22px"><div><h2>Aparelhos recentes</h2><p>Identificadores mascarados; localização e permissões permanecem ligadas ao usuário atual.</p></div></div><div class="epc-table-wrap"><table class="epc-table"><thead><tr><th>Usuário</th><th>Aparelho</th><th>Localização</th><th>Músicas</th><th>Último contato</th></tr></thead><tbody><?php foreach($devices as $d):?><tr><td><?=epca_e($d['user_name'])?><br><span class="epc-muted"><?=epca_e($d['username'])?></span></td><td><span class="epc-mono"><?=epca_e($d['device_name']?:epca_mask((string)$d['device_id']))?></span></td><td><?=epca_e($d['location_permission']??'unknown')?></td><td><?=epca_e($d['music_permission']??'unknown')?> · <?=intval($d['music_track_count']??0)?> faixas</td><td><span class="epc-badge <?=epca_online($d['last_seen_at']??null)?'ok':''?>"><?=epca_e($d['last_seen_at'])?></span></td></tr><?php endforeach;?></tbody></table></div></section>

<section id="estrada-viva" class="epc-section"><div class="epc-section-head"><div><h2>Estrada Viva e moderação</h2><p>Relatos do sistema e alertas comunitários do Server 7.0.</p></div></div><div class="epc-table-wrap"><table class="epc-table"><thead><tr><th>Relato</th><th>Local</th><th>Detalhes</th><th>Status</th><th>Moderação</th></tr></thead><tbody><?php if(!$reports):?><tr><td class="epc-empty" colspan="5">Nenhum relato técnico.</td></tr><?php endif;?><?php foreach($reports as $r):?><tr><td><strong>#<?=intval($r['id'])?> · <?=epca_e($r['type'])?></strong><br><span class="epc-muted"><?=epca_e($r['created_at'])?> · <?=epca_e($r['source'])?></span></td><td><a class="epc-coordinate" target="_blank" rel="noopener" href="<?=epca_e(epca_map((float)$r['latitude'],(float)$r['longitude']))?>"><?=number_format((float)$r['latitude'],5,',','')?>, <?=number_format((float)$r['longitude'],5,',','')?></a></td><td><?=epca_e($r['note']?:'—')?><?php if($r['limit_kmh']):?><br><span class="epc-muted">limite <?=intval($r['limit_kmh'])?> km/h</span><?php endif;?></td><td><span class="epc-badge <?=epca_status_class((string)$r['status'])?>"><?=epca_e($r['status'])?></span></td><td><div class="epc-inline"><?php foreach(['CONFIRMADO'=>'Confirmar','REJEITADO'=>'Rejeitar','PENDENTE'=>'Pendente'] as $st=>$lb):?><form method="post"><input type="hidden" name="csrf" value="<?=epca_e($csrf)?>"><input type="hidden" name="action" value="report_status"><input type="hidden" name="report_id" value="<?=intval($r['id'])?>"><input type="hidden" name="status" value="<?=$st?>"><button class="epc-btn small <?=$st==='CONFIRMADO'?'gold':($st==='REJEITADO'?'danger':'')?>" type="submit"><?=$lb?></button></form><?php endforeach;?></div></td></tr><?php endforeach;?></tbody></table></div>
<div class="epc-section-head" style="margin-top:22px"><div><h2>Alertas comunitários ativos</h2><p>Confirmações e descartes ajudam o app a calcular confiança.</p></div></div><div class="epc-table-wrap"><table class="epc-table"><thead><tr><th>Evento</th><th>Rodovia / local</th><th>Confiança comunitária</th><th>Validade</th><th>Ação</th></tr></thead><tbody><?php if(!$live):?><tr><td class="epc-empty" colspan="5">Nenhum alerta ativo agora.</td></tr><?php endif;?><?php foreach($live as $e):$positive=(int)$e['confirmations'];$negative=(int)$e['dismissals'];$score=($positive+1)/max(2,$positive+$negative+2);?><tr><td><strong>#<?=intval($e['id'])?> · <?=epca_e(epca_event_label((string)$e['event_type']))?></strong><br><span class="epc-muted"><?=epca_e($e['created_at'])?></span></td><td><?=epca_e($e['road']?:'Rodovia não informada')?><br><a class="epc-coordinate" target="_blank" rel="noopener" href="<?=epca_e(epca_map((float)$e['latitude'],(float)$e['longitude']))?>"><?=number_format((float)$e['latitude'],5,',','')?>, <?=number_format((float)$e['longitude'],5,',','')?></a></td><td><span class="epc-badge <?=$score>=.72?'ok':($score>=.5?'warn':'bad')?>"><?=number_format($score*100,0)?>%</span> <span class="epc-muted">+<?=$positive?> / -<?=$negative?></span></td><td><?=epca_e($e['expires_at'])?></td><td><form method="post" data-confirm="Remover este alerta comunitário agora?"><input type="hidden" name="csrf" value="<?=epca_e($csrf)?>"><input type="hidden" name="action" value="delete_live_event"><input type="hidden" name="event_id" value="<?=intval($e['id'])?>"><button class="epc-btn small danger" type="submit">Remover</button></form></td></tr><?php endforeach;?></tbody></table></div></section>

<section id="trafego-clima" class="epc-section"><div class="epc-section-head"><div><h2>Trânsito colaborativo</h2><p>Amostras opt-in, armazenadas somente com hash e retenção curta.</p></div></div><div class="epc-table-wrap"><table class="epc-table"><thead><tr><th>Trecho</th><th>Rodovia</th><th>Velocidade média</th><th>Amostras</th><th>Atualização</th></tr></thead><tbody><?php if(!$traffic):?><tr><td class="epc-empty" colspan="5">Sem amostras de trânsito ativas.</td></tr><?php endif;?><?php foreach($traffic as $t):$avg=(float)$t['avg_speed'];$limit=(float)$t['avg_limit'];$level=$avg<10?'PARADO':($avg<25?'MUITO LENTO':($avg<45?'LENTO':($avg<65?'MODERADO':'LIVRE')));?><tr><td><span class="epc-mono"><?=epca_e($t['cell_key'])?></span></td><td><?=epca_e($t['road']?:'—')?></td><td><strong><?=number_format($avg,1,',','')?> km/h</strong> <span class="epc-badge <?=epca_status_class($level)?>"><?=$level?></span><?php if($limit>0):?><br><span class="epc-muted">limite médio <?=number_format($limit,0)?> km/h</span><?php endif;?></td><td><?=intval($t['samples'])?></td><td><?=epca_e($t['updated_at'])?></td></tr><?php endforeach;?></tbody></table></div>
<div class="epc-section-head" style="margin-top:22px"><div><h2>Cache meteorológico</h2><p>O clima de rota é reaproveitado por 15 minutos para reduzir chamadas externas.</p></div><form method="post" data-confirm="Limpar todo o cache meteorológico?"><input type="hidden" name="csrf" value="<?=epca_e($csrf)?>"><input type="hidden" name="action" value="clear_weather"><button class="epc-btn small danger" type="submit">Limpar cache</button></form></div><div class="epc-table-wrap"><table class="epc-table"><thead><tr><th>Chave</th><th>Ponto</th><th>Coletado</th><th>Expira</th></tr></thead><tbody><?php if(!$weather):?><tr><td class="epc-empty" colspan="4">Cache vazio.</td></tr><?php endif;?><?php foreach($weather as $w):?><tr><td><span class="epc-mono"><?=epca_e($w['cache_key'])?></span></td><td><a class="epc-coordinate" target="_blank" rel="noopener" href="<?=epca_e(epca_map((float)$w['latitude'],(float)$w['longitude']))?>"><?=number_format((float)$w['latitude'],4,',','')?>, <?=number_format((float)$w['longitude'],4,',','')?></a></td><td><?=epca_e($w['fetched_at'])?></td><td><span class="epc-badge <?=strtotime((string)$w['expires_at'])>time()?'ok':'bad'?>"><?=epca_e($w['expires_at'])?></span></td></tr><?php endforeach;?></tbody></table></div></section>

<section id="combustivel" class="epc-section"><div class="epc-section-head"><div><h2>Combustível comunitário</h2><p>Preços informados nas últimas 36 horas, usando o mesmo ranking de rota do aplicativo.</p></div></div><div class="epc-table-wrap"><table class="epc-table"><thead><tr><th>Posto</th><th>Combustível</th><th>Preço</th><th>Local</th><th>Informado</th><th>Ação</th></tr></thead><tbody><?php if(!$fuel):?><tr><td class="epc-empty" colspan="6">Nenhum preço recente.</td></tr><?php endif;?><?php foreach($fuel as $f):?><tr><td><strong><?=epca_e($f['station'])?></strong></td><td><span class="epc-badge gold"><?=epca_e(strtoupper((string)$f['fuel']))?></span></td><td><strong>R$ <?=number_format((float)$f['price'],3,',','.')?></strong></td><td><a class="epc-coordinate" target="_blank" rel="noopener" href="<?=epca_e(epca_map((float)$f['latitude'],(float)$f['longitude']))?>"><?=number_format((float)$f['latitude'],5,',','')?>, <?=number_format((float)$f['longitude'],5,',','')?></a></td><td><?=epca_e($f['created_at'])?></td><td><form method="post" data-confirm="Remover este preço informado?"><input type="hidden" name="csrf" value="<?=epca_e($csrf)?>"><input type="hidden" name="action" value="delete_fuel"><input type="hidden" name="fuel_id" value="<?=intval($f['id'])?>"><button class="epc-btn small danger" type="submit">Remover</button></form></td></tr><?php endforeach;?></tbody></table></div></section>

<section id="radares" class="epc-section"><div class="epc-section-head"><div><h2>Radares e base rodoviária</h2><p>Resumo da base unificada. A edição detalhada continua disponível na Central de Radares.</p></div><a class="epc-btn gold" href="admin_radares.php">Abrir Central de Radares</a></div><?php $maxHaz=max(1,...array_values($hazardStats?:['OUTRO'=>1]));?><div class="epc-barlist"><?php if(!$hazardStats):?><div class="epc-muted">Nenhum ponto carregado.</div><?php endif;?><?php foreach($hazardStats as $type=>$count):?><div class="epc-bar-row"><span><?=epca_e($type)?></span><div class="epc-bar"><span style="width:<?=max(2,($count/$maxHaz)*100)?>%"></span></div><strong><?=intval($count)?></strong></div><?php endforeach;?></div><div class="epc-section-head" style="margin-top:22px"><div><h2>Sincronização por estado</h2><p>SP, RJ, MG e ES usam a mesma tabela road_hazards.</p></div></div><div class="epc-table-wrap"><table class="epc-table"><thead><tr><th>UF</th><th>Itens</th><th>Última tentativa</th><th>Último sucesso</th><th>Erro</th></tr></thead><tbody><?php foreach($hazardSync as $s):?><tr><td><strong><?=epca_e($s['uf'])?></strong></td><td><?=intval($s['item_count'])?></td><td><?=epca_e($s['last_attempt']?:'—')?></td><td><span class="epc-badge <?=$s['last_success']?'ok':'warn'?>"><?=epca_e($s['last_success']?:'Nunca')?></span></td><td class="epc-muted"><?=epca_e($s['last_error']?:'—')?></td></tr><?php endforeach;?></tbody></table></div></section>

<section id="comboios" class="epc-section"><div class="epc-section-head"><div><h2>Comboios ativos</h2><p>Grupos temporários e quantidade de participantes registrados no mesmo banco.</p></div></div><div class="epc-table-wrap"><table class="epc-table"><thead><tr><th>Código</th><th>Título</th><th>Membros</th><th>Criado</th><th>Expira</th><th>Ação</th></tr></thead><tbody><?php if(!$convoys):?><tr><td class="epc-empty" colspan="6">Nenhum comboio ativo.</td></tr><?php endif;?><?php foreach($convoys as $c):?><tr><td><strong class="epc-mono"><?=epca_e($c['code'])?></strong></td><td><?=epca_e($c['title']?:'Comboio Estrada Play')?></td><td><span class="epc-badge cyan"><?=intval($c['members'])?> membros</span></td><td><?=epca_e($c['created_at'])?></td><td><?=epca_e($c['expires_at'])?></td><td><form method="post" data-confirm="Encerrar este comboio e remover os membros ativos?"><input type="hidden" name="csrf" value="<?=epca_e($csrf)?>"><input type="hidden" name="action" value="close_convoy"><input type="hidden" name="convoy_id" value="<?=intval($c['id'])?>"><button class="epc-btn small danger" type="submit">Encerrar</button></form></td></tr><?php endforeach;?></tbody></table></div></section>

<section id="servidor" class="epc-section"><div class="epc-section-head"><div><h2>Servidor e manutenção</h2><p>Diagnóstico sem armazenar áudio ou vídeo. Ações abaixo operam no mesmo banco atual.</p></div><div class="epc-section-actions"><form method="post"><input type="hidden" name="csrf" value="<?=epca_e($csrf)?>"><input type="hidden" name="action" value="housekeeping"><button class="epc-btn gold" type="submit">Executar housekeeping</button></form><a class="epc-btn" href="admin_server.php">Diagnóstico completo</a></div></div><div class="epc-grid"><article class="epc-card"><span class="label">Servidor</span><div class="metric" style="font-size:20px"><?=epca_e(ESTRADAPLAY_SERVER_INTELLIGENT_VERSION)?></div><div class="sub">contexto de rota ativo</div></article><article class="epc-card"><span class="label">Banco</span><div class="metric" style="font-size:20px"><?=epca_e($health['db_h']??'0 B')?></div><div class="sub"><?=epca_e((string)db()->getAttribute(PDO::ATTR_DRIVER_NAME))?></div></article><article class="epc-card"><span class="label">Logs</span><div class="metric" style="font-size:20px"><?=epca_e($health['logs_h']??'0 B')?></div><div class="sub">rotação automática</div></article><article class="epc-card"><span class="label">Catálogo</span><div class="metric" style="font-size:20px"><?=intval($health['tracks']??0)?></div><div class="sub">metadados musicais</div></article></div><p class="epc-muted" style="margin-top:14px">Última sincronização do catálogo: <?=epca_e($health['last_sync']??'Nunca')?> · Pastas ativas: <?=intval($health['active_roots']??0)?> · Contexto: <?=intval($contextStats['active_live_events']??0)?> alertas / <?=intval($contextStats['active_traffic_samples']??0)?> amostras / <?=intval($contextStats['weather_cache_entries']??0)?> caches.</p></section>

<section id="auditoria" class="epc-section"><div class="epc-section-head"><div><h2>Auditoria</h2><p>Últimas ações administrativas e operações relevantes registradas pelo backend.</p></div></div><?php if(!$logs):?><div class="epc-muted">Nenhum registro.</div><?php endif;?><?php foreach($logs as $l):?><div class="epc-log"><span><?=epca_e($l['created_at'])?></span><strong><?=epca_e($l['action'])?></strong><code><?=epca_e($l['payload']?:'{}')?></code></div><?php endforeach;?></section>
<footer class="epc-footer">Estrada Play Comunista · Painel Administrativo EPC 1.0 · mesmo banco de dados da instalação atual</footer></main></div><script src="assets/js/admin-epc.js?v=1.0.0"></script></body></html>
