<?php
declare(strict_types=1);
require_once __DIR__.'/api/bootstrap.php';
ensure_default_users();
require_admin();
function rc_h(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
$rows=[];$stats=['total'=>0,'surface'=>0,'radar'=>0,'day'=>0];$available=false;
try{
 $driver=(string)db()->getAttribute(PDO::ATTR_DRIVER_NAME);
 if($driver==='mysql'){$q=db()->query("SHOW TABLES LIKE 'road_collective_events'");$available=(bool)$q->fetchColumn();}
 if($available){$stats['total']=(int)db()->query('SELECT COUNT(*) FROM road_collective_events')->fetchColumn();$stats['surface']=(int)db()->query("SELECT COUNT(*) FROM road_collective_events WHERE event_type='road_surface'")->fetchColumn();$stats['radar']=(int)db()->query("SELECT COUNT(*) FROM road_collective_events WHERE event_type='radar_confirmation'")->fetchColumn();$stats['day']=(int)db()->query("SELECT COUNT(*) FROM road_collective_events WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)")->fetchColumn();$rows=db()->query('SELECT * FROM road_collective_events ORDER BY id DESC LIMIT 250')->fetchAll()?:[];}
}catch(Throwable $e){$available=false;}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Inteligência Coletiva - EstradaPlay</title><link rel="stylesheet" href="assets/css/app.css?v=1.0.0"><style>.cg{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.cc{padding:14px}.cc strong{display:block;font-size:1.45rem}.small{font-size:.82rem}.coord{white-space:nowrap}</style></head><body data-role="admin"><main class="admin-main"><div class="toolbar admin-toolbar"><div><p class="eyebrow">ESTRADAPLAY · SERVIDOR 500 MB V4</p><h1>Inteligência Coletiva</h1><p class="muted">Eventos leves de qualidade da via e confirmações de radar. Nenhum vídeo é recebido aqui.</p></div><div class="row"><a class="button secondary" href="admin_server.php">Central</a><a class="button secondary" href="admin_reports.php">Reportes</a></div></div><?php if(!$available):?><div class="panel">A tabela coletiva ainda não existe. Ela será criada automaticamente quando o primeiro aparelho 1.5.0 enviar um evento.</div><?php else:?><section class="panel"><div class="cg"><article class="panel cc"><span class="muted">Total</span><strong><?=$stats['total']?></strong></article><article class="panel cc"><span class="muted">Irregularidades</span><strong><?=$stats['surface']?></strong></article><article class="panel cc"><span class="muted">Confirmações radar</span><strong><?=$stats['radar']?></strong></article><article class="panel cc"><span class="muted">Últimas 24h</span><strong><?=$stats['day']?></strong></article></div></section><section class="panel"><div class="table-wrap"><table><thead><tr><th>ID</th><th>Evento</th><th>Local</th><th>Dados</th><th>Quando</th></tr></thead><tbody><?php foreach($rows as $r):$lat=(float)$r['latitude'];$lon=(float)$r['longitude'];$map='https://www.openstreetmap.org/?mlat='.$lat.'&mlon='.$lon.'#map=17/'.$lat.'/'.$lon;?><tr><td>#<?= (int)$r['id']?></td><td><strong><?=rc_h((string)$r['event_type'])?></strong><?php if(!empty($r['answer'])):?><br><small><?=rc_h((string)$r['answer'])?></small><?php endif;?></td><td class="coord"><a href="<?=rc_h($map)?>" target="_blank" rel="noopener"><?=number_format($lat,6,'.','')?>, <?=number_format($lon,6,'.','')?></a></td><td class="small"><?php if($r['severity']!==null):?>Impacto: <?=number_format((float)$r['severity'],1,',','')?>/10<br><?php endif;?><?php if($r['speed_kmh']!==null):?>Velocidade: <?=number_format((float)$r['speed_kmh'],0,',','')?> km/h<br><?php endif;?><?php if(!empty($r['road'])):?><?=rc_h((string)$r['road'])?><br><?php endif;?><?php if(!empty($r['radar_id'])):?>Radar: <?=rc_h((string)$r['radar_id'])?><?php endif;?></td><td><?=rc_h((string)$r['created_at'])?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?></main></body></html>