<?php
declare(strict_types=1);require_once __DIR__.'/api/bootstrap.php';ensure_default_users();$user=require_admin();$pdo=db();
$message='';if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$enabled=($_POST['enabled']??'1')==='1'?'1':'0';set_app_setting('radio_enabled',$enabled);$message=$enabled==='1'?'Rádio liberado.':'Rádio desativado pelo servidor.';}
$enabled=app_setting('radio_enabled','1')!=='0';$rooms=[];$alerts=[];try{$cut=date('Y-m-d H:i:s',time()-20);$q=$pdo->prepare('SELECT room_key,road,direction,segment,COUNT(*) participants,MAX(last_seen_at) last_seen FROM radio_presence WHERE last_seen_at>=? GROUP BY room_key,road,direction,segment ORDER BY participants DESC,last_seen DESC LIMIT 100');$q->execute([$cut]);$rooms=$q->fetchAll()?:[];$q=$pdo->query('SELECT room_key,alert_type,created_at,expires_at FROM radio_alerts WHERE expires_at>=NOW() ORDER BY id DESC LIMIT 100');$alerts=$q->fetchAll()?:[];}catch(Throwable $e){}
function ar_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Rádio da Rodovia</title><link rel="stylesheet" href="assets/css/app.css?v=1.0.0"><style>.rgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px}.rtable td,.rtable th{vertical-align:top}.on{color:#45d483}.off{color:#ff646b}</style></head><body data-role="admin"><main class="admin-main"><div class="toolbar admin-toolbar"><div><p class="eyebrow">ESTRADAPLAY · SERVER V5</p><h1>Rádio da Rodovia</h1><p class="muted">Presença e sinalização WebRTC. O servidor não recebe nem grava o áudio dos motoristas.</p></div><div class="row"><a class="button secondary" href="admin_server.php">Central do Servidor</a><a class="button secondary" href="admin.php">Painel Admin</a></div></div>
<?php if($message):?><div class="panel success"><?=ar_h($message)?></div><?php endif;?>
<section class="panel"><div class="rgrid"><article class="panel"><span class="muted">Estado</span><h2 class="<?=$enabled?'on':'off'?>"><?=$enabled?'ATIVO':'DESATIVADO'?></h2></article><article class="panel"><span class="muted">Salas ativas</span><h2><?=count($rooms)?></h2></article><article class="panel"><span class="muted">Motoristas conectados</span><h2><?=array_sum(array_map(fn($r)=>(int)$r['participants'],$rooms))?></h2></article><article class="panel"><span class="muted">Áudio armazenado</span><h2>NÃO</h2></article></div><form method="post"><input type="hidden" name="csrf" value="<?=ar_h(csrf_token())?>"><input type="hidden" name="enabled" value="<?=$enabled?'0':'1'?>"><button class="button <?=$enabled?'secondary':''?>" type="submit"><?=$enabled?'DESATIVAR RÁDIO':'ATIVAR RÁDIO'?></button></form></section>
<section class="panel"><h2>Salas por trecho</h2><div class="table-wrap"><table class="rtable"><thead><tr><th>Rodovia</th><th>Sentido</th><th>Trecho</th><th>Participantes</th><th>Último sinal</th></tr></thead><tbody><?php if(!$rooms):?><tr><td colspan="5">Nenhuma sala ativa agora.</td></tr><?php endif;?><?php foreach($rooms as $r):?><tr><td><strong><?=ar_h($r['road'])?></strong></td><td><?=ar_h($r['direction'])?></td><td><?=ar_h($r['segment'])?></td><td><?= (int)$r['participants']?> / 8</td><td><?=ar_h($r['last_seen'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2>Alertas rápidos ativos</h2><p class="muted">Expiram em 30 minutos e não entram automaticamente na base permanente de perigos.</p><div class="table-wrap"><table class="rtable"><thead><tr><th>Sala</th><th>Tipo</th><th>Quando</th><th>Expira</th></tr></thead><tbody><?php if(!$alerts):?><tr><td colspan="4">Nenhum alerta temporário ativo.</td></tr><?php endif;?><?php foreach($alerts as $a):?><tr><td><?=ar_h($a['room_key'])?></td><td><strong><?=ar_h($a['alert_type'])?></strong></td><td><?=ar_h($a['created_at'])?></td><td><?=ar_h($a['expires_at'])?></td></tr><?php endforeach;?></tbody></table></div></section>
</main></body></html>
