package com.estradaplay.patriota;

import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import java.util.Locale;

public final class EmergencyActivity extends ComponentActivity {
    private final int BG=Color.rgb(8,5,7),SURFACE=Color.rgb(18,9,12),SURFACE2=Color.rgb(28,14,18),BORDER=Color.rgb(76,38,44),TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38),GREEN=Color.rgb(72,212,134),GOLD=Color.rgb(226,185,76);private double lat=Double.NaN,lon=Double.NaN;
    @Override protected void onCreate(Bundle b){super.onCreate(b);seed();build();}
    private void seed(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;try{LocationManager m=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;for(String p:new String[]{LocationManager.GPS_PROVIDER,LocationManager.NETWORK_PROVIDER}){Location x=m.getLastKnownLocation(p);if(x!=null&&(best==null||x.getTime()>best.getTime()))best=x;}if(best!=null){lat=best.getLatitude();lon=best.getLongitude();}}catch(Throwable ignored){}}
    private void build(){ScrollView sv=new ScrollView(this);LinearLayout page=col();page.setPadding(dp(18),dp(16),dp(18),dp(28));page.setBackgroundColor(BG);sv.addView(page);setContentView(UnifiedAppShell.wrap(this,"central",sv));LinearLayout h=row();Button back=btn("‹ CENTRAL",false);h.addView(back,new LinearLayout.LayoutParams(dp(100),dp(46)));back.setOnClickListener(v->finish());LinearLayout tt=col();tt.addView(over("SOS RODOVIÁRIO",RED));tt.addView(text("Ajuda na estrada",28,TEXT,true));tt.addView(text("Use somente quando estiver parado em local seguro sempre que possível.",11,MUTED,false));h.addView(tt,new LinearLayout.LayoutParams(0,-2,1));page.addView(h);
        LinearLayout loc=card();loc.addView(over(Double.isFinite(lat)?"LOCALIZAÇÃO PRONTA":"AGUARDANDO GPS",Double.isFinite(lat)?GREEN:GOLD));String road=KnownRoadCatalog.selected(this);loc.addView(text(road.isEmpty()?"Rodovia não definida":road,18,TEXT,true));loc.addView(text(Double.isFinite(lat)?String.format(Locale.US,"%.6f, %.6f",lat,lon):"Abra o mapa/Estrada por alguns segundos para obter uma posição.",12,MUTED,false));Button share=btn("COMPARTILHAR MINHA LOCALIZAÇÃO",true);add(loc,share,0,12,0,0,-1,dp(56));share.setOnClickListener(v->share());Button copy=btn("COPIAR COORDENADAS",false);add(loc,copy,0,8,0,0,-1,dp(48));copy.setOnClickListener(v->copy());add(page,loc,0,14,0,16,-1,-2);
        page.addView(over("TELEFONES DE EMERGÊNCIA",MUTED));LinearLayout calls=card();Button prf=btn("PRF · 191",false);Button samu=btn("SAMU · 192",false);Button fire=btn("BOMBEIROS · 193",false);Button police=btn("POLÍCIA · 190",false);calls.addView(prf,new LinearLayout.LayoutParams(-1,dp(52)));add(calls,samu,0,7,0,0,-1,dp(52));add(calls,fire,0,7,0,0,-1,dp(52));add(calls,police,0,7,0,0,-1,dp(52));prf.setOnClickListener(v->dial("191"));samu.setOnClickListener(v->dial("192"));fire.setOnClickListener(v->dial("193"));police.setOnClickListener(v->dial("190"));add(page,calls,0,8,0,14,-1,-2);
        LinearLayout services=card();services.addView(text("Precisa de guincho, oficina, borracharia, posto ou hospital?",14,TEXT,true));Button near=btn("VER SERVIÇOS PRÓXIMOS",false);add(services,near,0,10,0,0,-1,dp(52));near.setOnClickListener(v->startActivity(new Intent(this,NearbyServicesActivity.class)));add(page,services,0,0,0,0,-1,-2);
    }
    private void share(){if(!Double.isFinite(lat)||!Double.isFinite(lon)){toast("Ainda não tenho uma posição GPS válida.");return;}String road=KnownRoadCatalog.selected(this);String msg="Preciso de ajuda na estrada."+(road.isEmpty()?"":" Rodovia: "+road+".")+" Localização: "+String.format(Locale.US,"%.6f, %.6f",lat,lon)+" https://maps.google.com/?q="+String.format(Locale.US,"%.6f,%.6f",lat,lon);Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,msg);startActivity(Intent.createChooser(i,"Compartilhar localização"));}
    private void copy(){if(!Double.isFinite(lat)||!Double.isFinite(lon)){toast("Sem GPS válido.");return;}android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm!=null)cm.setPrimaryClip(ClipData.newPlainText("Localização Estrada Play",String.format(Locale.US,"%.6f, %.6f",lat,lon)));toast("Coordenadas copiadas.");}
    private void dial(String n){try{startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+n)));}catch(Throwable e){toast("Não consegui abrir o discador.");}}
    private LinearLayout card(){LinearLayout c=col();c.setPadding(dp(15),dp(14),dp(15),dp(14));c.setBackground(panel(SURFACE,16,BORDER));return c;}private Button btn(String v,boolean pri){Button b=new Button(this);b.setAllCaps(false);b.setText(v);b.setTextColor(TEXT);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(panel(pri?RED:SURFACE2,13,pri?0:BORDER));return b;}private TextView text(String v,float s,int c,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private TextView over(String v,int c){TextView t=text(v,9,c,true);t.setLetterSpacing(.12f);return t;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private GradientDrawable panel(int c,int r,int st){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(st!=0)g.setStroke(dp(1),st);return g;}private void add(LinearLayout p,View v,int l,int t,int r,int b,int w,int h){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(w,h);x.setMargins(dp(l),dp(t),dp(r),dp(b));p.addView(v,x);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
