package com.estradaplay.patriota;

import android.content.Context;import android.content.SharedPreferences;import org.json.*;import java.util.*;

final class FuelCommunityStore {
    private static final String PREF="epp_fuel_live_v190",Q="queue",C="cache";private final Context app;private final SharedPreferences p;
    static final class Price {final long id,at;final String station,fuel;final double price,lat,lon,distanceM;Price(long id,String station,String fuel,double price,double lat,double lon,long at,double distanceM){this.id=id;this.station=station;this.fuel=fuel;this.price=price;this.lat=lat;this.lon=lon;this.at=at;this.distanceM=distanceM;}}
    FuelCommunityStore(Context c){app=c.getApplicationContext();p=app.getSharedPreferences(PREF,Context.MODE_PRIVATE);}
    synchronized void report(double lat,double lon,String station,String fuel,double price){try{JSONObject o=new JSONObject();o.put("station",station==null?"":station.trim());o.put("fuel",fuel==null?"":fuel.trim());o.put("price",price);o.put("lat",lat);o.put("lon",lon);o.put("at",System.currentTimeMillis());JSONArray old=queue(),out=new JSONArray();out.put(o);for(int i=0;i<old.length()&&out.length()<30;i++)out.put(old.opt(i));p.edit().putString(Q,out.toString()).apply();}catch(Throwable ignored){}}
    synchronized int queued(){return queue().length();}
    synchronized boolean sync(ApiClient api,double lat,double lon){if(api==null)return false;JSONArray a=queue(),keep=new JSONArray();boolean any=false;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;try{ApiClient.Response r=api.post("api/fuel_live.php?action=report",o);if(r.ok()&&r.json().optBoolean("ok",false)){any=true;continue;}}catch(Throwable ignored){}keep.put(o);}p.edit().putString(Q,keep.toString()).apply();try{String path=String.format(Locale.US,"api/fuel_live.php?action=near&lat=%.6f&lon=%.6f&radius=30000",lat,lon);ApiClient.Response r=api.get(path);JSONObject j=r.json();JSONArray rows=j.optJSONArray("prices");if(r.ok()&&j.optBoolean("ok",false)&&rows!=null){p.edit().putString(C,rows.toString()).apply();any=true;}}catch(Throwable ignored){}return any;}
    synchronized ArrayList<Price> cached(double lat,double lon){ArrayList<Price> out=new ArrayList<>();JSONArray a;try{a=new JSONArray(p.getString(C,"[]"));}catch(Throwable e){a=new JSONArray();}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;double la=o.optDouble("lat",Double.NaN),lo=o.optDouble("lon",Double.NaN);double d=Double.isFinite(la)&&Double.isFinite(lo)?RoadPackStore.distanceM(lat,lon,la,lo):Double.POSITIVE_INFINITY;out.add(new Price(o.optLong("id"),o.optString("station","Posto"),o.optString("fuel","Combustível"),o.optDouble("price"),la,lo,o.optLong("at"),d));}out.sort(Comparator.comparingDouble(x->x.price));return out;}
    private JSONArray queue(){try{return new JSONArray(p.getString(Q,"[]"));}catch(Throwable e){return new JSONArray();}}
}
