package com.estradaplay.patriota;

import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import java.text.SimpleDateFormat;import java.util.*;

public final class MaintenanceActivity extends ComponentActivity {
    private final int BG=Color.rgb(8,5,7),SURFACE=Color.rgb(18,9,12),SURFACE2=Color.rgb(28,14,18),BORDER=Color.rgb(76,38,44),TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38),GREEN=Color.rgb(72,212,134),GOLD=Color.rgb(226,185,76);
    private LinearLayout page;
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);build();}
    private void build(){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);page=col();page.setPadding(dp(18),dp(16),dp(18),dp(28));page.setBackgroundColor(BG);sv.addView(page);setContentView(UnifiedAppShell.wrap(this,"central",sv));VehicleProfileStore.Profile v=VehicleProfileStore.active(this);double current=MaintenanceStore.currentOdometer(this,v.id);
        LinearLayout head=row();head.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("‹ CENTRAL",false);head.addView(back,new LinearLayout.LayoutParams(dp(100),dp(46)));back.setOnClickListener(x->finish());LinearLayout tt=col();tt.addView(over("DIÁRIO DO CARRO",RED));tt.addView(text("Manutenção",27,TEXT,true));tt.addView(text(v.name+" · "+(current>0?String.format(Locale.getDefault(),"%.0f km",current):"odômetro ainda não informado"),11,MUTED,false));head.addView(tt,new LinearLayout.LayoutParams(0,-2,1));page.addView(head);
        int due=MaintenanceStore.dueCount(this,v.id);LinearLayout alert=card();alert.addView(over(due>0?"ATENÇÃO":"EM DIA",due>0?GOLD:GREEN));alert.addView(text(due>0?due+" item(ns) chegando ao prazo":"Nenhuma manutenção próxima do prazo",18,TEXT,true));alert.addView(text("Os lembretes ficam somente neste aparelho e usam o odômetro registrado nos abastecimentos ou revisões.",10,MUTED,false));add(page,alert,0,14,0,16,-1,-2);
        page.addView(over("REGISTRAR SERVIÇO",MUTED));LinearLayout form=card();Spinner type=new Spinner(this);String[] types={"Óleo e filtro","Filtro de ar","Pneus","Freios","Correia dentada","Bateria","Revisão geral","Outro"};ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,types);type.setAdapter(a);form.addView(type,new LinearLayout.LayoutParams(-1,dp(52)));EditText odo=field("ODÔMETRO AGORA","km",current>0?String.format(Locale.US,"%.0f",current):"");EditText interval=field("PRÓXIMA EM","intervalo em km","10000");EditText months=field("OU EM","meses","12");EditText note=fieldText("OBSERVAÇÃO","Ex.: óleo 5W30, filtro trocado");form.addView(odo);form.addView(interval);form.addView(months);form.addView(note);Button save=btn("SALVAR MANUTENÇÃO",true);add(form,save,0,12,0,0,-1,dp(56));save.setOnClickListener(x->{try{double km=num(odo),iv=num(interval);int mo=(int)num(months);MaintenanceStore.add(this,v.id,String.valueOf(type.getSelectedItem()),km,iv,mo,note.getText().toString().trim());Toast.makeText(this,"Manutenção registrada.",Toast.LENGTH_SHORT).show();build();}catch(Throwable e){Toast.makeText(this,"Confira os valores informados.",Toast.LENGTH_LONG).show();}});add(page,form,0,8,0,18,-1,-2);
        page.addView(over("HISTÓRICO",MUTED));ArrayList<MaintenanceStore.Entry> rows=MaintenanceStore.list(this,v.id);if(rows.isEmpty())page.addView(text("Nenhum serviço registrado ainda.",12,MUTED,false));long now=System.currentTimeMillis();for(int i=0;i<Math.min(16,rows.size());i++){MaintenanceStore.Entry e=rows.get(i);LinearLayout c=card();boolean soon=e.soon(current,now);c.addView(text(e.type,16,soon?GOLD:TEXT,true));String when=new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(new Date(e.at));StringBuilder d=new StringBuilder(when);if(e.odometer>0)d.append(" · ").append(Math.round(e.odometer)).append(" km");if(e.nextKm>0)d.append("\nPróxima: ").append(Math.round(e.nextKm)).append(" km");if(e.nextAt>0)d.append(" · ").append(new SimpleDateFormat("MM/yyyy",Locale.getDefault()).format(new Date(e.nextAt)));c.addView(text(d.toString(),11,soon?GOLD:MUTED,false));if(!e.note.isEmpty())c.addView(text(e.note,11,TEXT,false));add(page,c,0,8,0,0,-1,-2);}
    }
    private EditText field(String label,String hint,String value){EditText e=new EditText(this);e.setHint(label+" · "+hint);e.setText(value);e.setSingleLine(true);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setBackground(panel(SURFACE2,12,BORDER));e.setPadding(dp(12),0,dp(12),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(8),0,0);e.setLayoutParams(p);return e;}private EditText fieldText(String label,String hint){EditText e=new EditText(this);e.setHint(label+" · "+hint);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setSingleLine(true);e.setBackground(panel(SURFACE2,12,BORDER));e.setPadding(dp(12),0,dp(12),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(8),0,0);e.setLayoutParams(p);return e;}
    private double num(EditText e){String s=e.getText().toString().trim().replace(',','.');return s.isEmpty()?0:Double.parseDouble(s);}private LinearLayout card(){LinearLayout c=col();c.setPadding(dp(15),dp(14),dp(15),dp(14));c.setBackground(panel(SURFACE,16,BORDER));return c;}private Button btn(String v,boolean pri){Button b=new Button(this);b.setAllCaps(false);b.setText(v);b.setTextColor(TEXT);b.setTextSize(10);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setStateListAnimator(null);b.setBackground(panel(pri?RED:SURFACE2,13,pri?0:BORDER));return b;}private TextView text(String v,float s,int c,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private TextView over(String v,int c){TextView t=text(v,9,c,true);t.setLetterSpacing(.12f);return t;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private GradientDrawable panel(int c,int r,int st){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(st!=0)g.setStroke(dp(1),st);return g;}private void add(LinearLayout p,View v,int l,int t,int r,int b,int w,int h){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(w,h);x.setMargins(dp(l),dp(t),dp(r),dp(b));p.addView(v,x);}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
