package com.estradaplay.comunista;

import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import java.util.*;

public final class DriveToolsActivity extends ComponentActivity {
    private final int BG=Color.rgb(8,5,7),SURFACE=Color.rgb(18,9,12),SURFACE2=Color.rgb(28,14,18),BORDER=Color.rgb(76,38,44),TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38),GREEN=Color.rgb(72,212,134),GOLD=Color.rgb(226,185,76);
    private LinearLayout page;
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);build();}
    private void build(){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setOverScrollMode(View.OVER_SCROLL_NEVER);page=col();page.setPadding(dp(18),dp(16),dp(18),dp(28));page.setBackgroundColor(BG);sv.addView(page);setContentView(UnifiedAppShell.wrap(this,"central",sv));
        LinearLayout head=row();head.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("‹ VOLTAR",false);head.addView(back,new LinearLayout.LayoutParams(dp(94),dp(46)));back.setOnClickListener(v->finish());LinearLayout title=col();title.addView(over("CENTRAL DE BORDO",RED));title.addView(text("Controles da viagem",27,TEXT,true));title.addView(text("Só o que você precisa, organizado por função.",11,MUTED,false));head.addView(title,new LinearLayout.LayoutParams(0,-2,1));page.addView(head);
        addStatusStrip();section("VIAGEM");grid(new Tool[]{new Tool("PLANEJAR VIAGEM","Destino, distância e custo",TripPlannerActivity.class,GOLD),new Tool("HISTÓRICO","Viagens e replay",TripHistoryActivity.class,GREEN),new Tool("FAVORITOS","Postos e paradas salvas",RoadFavoritesActivity.class,GOLD)});section("VEÍCULO");grid(new Tool[]{new Tool("VEÍCULO","Consumo e abastecimento",VehicleCostActivity.class,RED),new Tool("MANUTENÇÃO","Diário e próximos serviços",MaintenanceActivity.class,GOLD),new Tool("COMBUSTÍVEL","Preços informados na estrada",FuelCommunityActivity.class,GREEN),new Tool("OBD2","ELM327 Bluetooth · somente leitura",Obd2Activity.class,GREEN)});
        section("ESTRADA");grid(new Tool[]{new Tool("SOS","Localização e emergência",EmergencyActivity.class,RED),new Tool("OFFLINE","RJ · MG · ES e teste local",OfflineCenterActivity.class,GREEN),new Tool("ESTRADA VIVA","Alertas comunitários no mapa",EstradaVivaActivity.class,RED),new Tool("RADARES","Confirmações da base coletiva",CollectiveRoadActivity.class,GOLD),new Tool("SERVIÇOS","Postos, oficinas e hospitais",NearbyServicesActivity.class,GREEN),new Tool("REPORTAR","Registrar ocorrência da via",RoadReportActivity.class,RED)});
        section("BORDO");grid(new Tool[]{new Tool("RÁDIO PTT","Canal da rodovia",RoadRadioActivity.class,GREEN),new Tool("COMBOIO","Mapa ao vivo entre os carros",ConvoyActivity.class,GREEN),new Tool("HUD","Projeção no para-brisa",HudActivity.class,GOLD),new Tool("DASHCAM","Câmera e salvar momento",CameraActivity.class,RED),new Tool("COPILOTO","Comandos de voz",VoiceCommandActivity.class,GREEN)});
        section("AJUSTES RÁPIDOS");toggle("MODO NOTURNO","Escurecer instrumentos automaticamente","auto_night",DriveSettings.autoNight(this));toggle("CHUVA AUTOMÁTICA","Aumentar antecedência quando houver precipitação","rain_auto",DriveSettings.autoRain(this));toggle("PROTEGER VÍDEO EM IMPACTO","Preservar trecho da dashcam quando estiver aberta","protect_impact_video",DriveSettings.protectImpactVideo(this));toggle("BASE COLETIVA","Compartilhar somente eventos leves da estrada","collective_enabled",DriveSettings.collectiveEnabled(this));
        LinearLayout maintenance=row();Button voice=btn("DIAGNÓSTICO DE VOZ",false);Button server=btn("SERVIDOR",false);maintenance.addView(voice,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(50),1);sp.setMargins(dp(8),0,0,0);maintenance.addView(server,sp);voice.setOnClickListener(v->open(VoiceDiagnosticsActivity.class));server.setOnClickListener(v->open(ServerSettingsActivity.class));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(-1,-2);mp.setMargins(0,dp(14),0,0);page.addView(maintenance,mp);
    }
    private void addStatusStrip(){LinearLayout strip=row();strip.setGravity(Gravity.CENTER_VERTICAL);strip.setPadding(dp(12),dp(10),dp(12),dp(10));strip.setBackground(panel(SURFACE2,14,BORDER));TextView a=over("● PROTEÇÃO",GREEN);strip.addView(a,new LinearLayout.LayoutParams(0,-2,1));TextView b=over(DriveSettings.offlineTestMode(this)?"TESTE OFFLINE":"BASE LOCAL",DriveSettings.offlineTestMode(this)?GOLD:MUTED);b.setGravity(Gravity.RIGHT);strip.addView(b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(14),0,0);page.addView(strip,p);}
    private void section(String name){TextView s=over(name,MUTED);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(20),0,dp(8));page.addView(s,p);}
    private void grid(Tool[] tools){int cols=getResources().getDisplayMetrics().widthPixels/getResources().getDisplayMetrics().density>=700?3:2;for(int i=0;i<tools.length;i+=cols){LinearLayout r=row();for(int c=0;c<cols;c++){int k=i+c;if(k>=tools.length){r.addView(new View(this),new LinearLayout.LayoutParams(0,1,1));continue;}View card=tool(tools[k]);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(112),1);if(c>0)p.setMargins(dp(8),0,0,0);r.addView(card,p);}LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);if(i>0)rp.setMargins(0,dp(8),0,0);page.addView(r,rp);}}
    private View tool(Tool t){LinearLayout c=col();c.setPadding(dp(14),dp(13),dp(14),dp(12));c.setBackground(panel(SURFACE,16,BORDER));TextView mark=text("●",12,t.accent,true);c.addView(mark);TextView title=text(t.title,15,TEXT,true);c.addView(title);TextView sub=text(t.sub,10,MUTED,false);sub.setMaxLines(2);c.addView(sub,new LinearLayout.LayoutParams(-1,0,1));TextView go=over("ABRIR  ›",t.accent);c.addView(go);c.setClickable(true);c.setOnClickListener(v->open(t.cls));return c;}
    private void toggle(String title,String sub,String key,boolean initial){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(14),dp(11),dp(10),dp(11));r.setBackground(panel(SURFACE,14,BORDER));LinearLayout m=col();m.addView(text(title,14,TEXT,true));m.addView(text(sub,10,MUTED,false));r.addView(m,new LinearLayout.LayoutParams(0,-2,1));Button b=btn(initial?"ATIVO":"DESLIGADO",initial);r.addView(b,new LinearLayout.LayoutParams(dp(104),dp(44)));final boolean[] on={initial};b.setOnClickListener(v->{on[0]=!on[0];DriveSettings.toggle(this,key,on[0]);style(b,on[0]);b.setText(on[0]?"ATIVO":"DESLIGADO");});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));page.addView(r,p);}
    private void open(Class<?> c){try{startActivity(new Intent(this,c));}catch(Throwable e){Toast.makeText(this,"Essa função não conseguiu abrir. Vou manter a Central funcionando.",Toast.LENGTH_LONG).show();}}
    private Button btn(String v,boolean primary){Button b=new Button(this);b.setAllCaps(false);b.setText(v);b.setTextSize(10);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setStateListAnimator(null);style(b,primary);return b;}private void style(Button b,boolean primary){b.setTextColor(primary?Color.WHITE:TEXT);b.setBackground(panel(primary?RED:SURFACE2,13,primary?0:BORDER));}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private TextView text(String v,float s,int c,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);t.setGravity(Gravity.CENTER_VERTICAL);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private TextView over(String v,int c){TextView t=text(v,9,c,true);t.setLetterSpacing(.12f);return t;}private GradientDrawable panel(int c,int r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(stroke!=0)g.setStroke(dp(1),stroke);return g;}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}private static final class Tool{final String title,sub;final Class<?>cls;final int accent;Tool(String t,String s,Class<?>c,int a){title=t;sub=s;cls=c;accent=a;}}
}
