package com.estradaplay.comunista;
import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;
public final class DriveToolsActivity extends ComponentActivity{
    private LinearLayout page;private int TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38);
    @Override protected void onCreate(Bundle b){super.onCreate(b);build();}
    private void build(){ScrollView s=new ScrollView(this);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(20),dp(20),dp(20),dp(30));page.setBackgroundColor(Color.rgb(9,5,7));s.addView(page);setContentView(s);page.addView(t("CENTRAL INTELIGENTE",27,TEXT,true));page.addView(t("Preferências locais de condução",12,MUTED,false));check("MODO NOTURNO AUTOMÁTICO","Escurece instrumentos à noite.","auto_night",DriveSettings.autoNight(this));check("HUD ESPELHADO","Inverte o HUD para refletir no para-brisa.","hud_mirror",DriveSettings.hudMirror(this));button("ABRIR HUD",HudActivity.class);button("HISTÓRICO DE VIAGENS",TripHistoryActivity.class);button("REPORTAR PONTO DA VIA",RoadReportActivity.class);button("CÂMERA / DASHCAM",CameraActivity.class);button("SERVIÇOS PRÓXIMOS",NearbyServicesActivity.class);button("COMANDO DE VOZ",VoiceCommandActivity.class);}
    private void check(String title,String sub,String key,boolean initial){CheckBox c=new CheckBox(this);c.setText(title+"\n"+sub);c.setTextColor(TEXT);c.setTextSize(14);c.setChecked(initial);c.setPadding(0,dp(10),0,dp(10));c.setOnCheckedChangeListener((b,v)->DriveSettings.toggle(this,key,v));page.addView(c,new LinearLayout.LayoutParams(-1,-2));}
    private void button(String label,Class<?> cls){Button b=new Button(this);b.setText(label);b.setTextColor(TEXT);b.setBackgroundColor(Color.rgb(62,14,23));b.setOnClickListener(v->startActivity(new Intent(this,cls)));page.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));}
    private TextView t(String v,float s,int c,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
