package com.estradaplay.comunista;

import android.Manifest;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.*;

public final class FuelCommunityActivity extends ComponentActivity {
    private final int BG=Color.rgb(8,5,7),SURFACE=Color.rgb(18,9,12),SURFACE2=Color.rgb(28,14,18),BORDER=Color.rgb(76,38,44),TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38),GREEN=Color.rgb(72,212,134),GOLD=Color.rgb(226,185,76);private final ExecutorService io=Executors.newSingleThreadExecutor();private LinearLayout page;private FuelCommunityStore store;private double lat=Double.NaN,lon=Double.NaN;
    @Override protected void onCreate(Bundle b){super.onCreate(b);store=new FuelCommunityStore(this);seed();build();}@Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
    private void seed(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;try{LocationManager m=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;for(String p:new String[]{LocationManager.GPS_PROVIDER,LocationManager.NETWORK_PROVIDER}){Location x=m.getLastKnownLocation(p);if(x!=null&&(best==null||x.getTime()>best.getTime()))best=x;}if(best!=null){lat=best.getLatitude();lon=best.getLongitude();}}catch(Throwable ignored){}}
    private void build(){ScrollView sv=new ScrollView(this);page=col();page.setPadding(dp(18),dp(16),dp(18),dp(28));page.setBackgroundColor(BG);sv.addView(page);setContentView(UnifiedAppShell.wrap(this,"central",sv));LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("‹ CENTRAL",false);h.addView(back,new LinearLayout.LayoutParams(dp(100),dp(46)));back.setOnClickListener(v->finish());LinearLayout tt=col();tt.addView(over("COMBUSTÍVEL COMUNITÁRIO",RED));tt.addView(text("Preço na estrada",27,TEXT,true));tt.addView(text("Relatos recentes de motoristas. Confira o valor no posto antes de abastecer.",11,MUTED,false));h.addView(tt,new LinearLayout.LayoutParams(0,-2,1));page.addView(h);
        LinearLayout report=card();report.addView(over("INFORMAR PREÇO",GOLD));EditText station=field("Nome do posto ou referência",false);Spinner fuel=new Spinner(this);String[] fuels={"Gasolina comum","Gasolina aditivada","Etanol","Diesel S10","Diesel S500","GNV"};fuel.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,fuels));report.addView(fuel,new LinearLayout.LayoutParams(-1,dp(50)));EditText price=field("Preço por litro/m³",true);report.addView(station);report.addView(price);Button send=btn("PUBLICAR PREÇO",true);add(report,send,0,10,0,0,-1,dp(56));send.setOnClickListener(v->{if(!Double.isFinite(lat)||!Double.isFinite(lon)){toast("Ainda não tenho uma posição GPS válida.");return;}String st=station.getText().toString().trim();double pr;try{pr=Double.parseDouble(price.getText().toString().trim().replace(',','.'));}catch(Throwable e){toast("Informe um preço válido.");return;}if(st.length()<2||pr<1||pr>20){toast("Confira o nome do posto e o preço.");return;}store.report(lat,lon,st,String.valueOf(fuel.getSelectedItem()),pr);toast("Preço salvo. Sincronizando…");refresh(true);});add(page,report,0,14,0,14,-1,-2);
        LinearLayout strip=card();strip.addView(text(store.queued()>0?store.queued()+" relato(s) aguardando internet":"Fila de envio vazia",12,store.queued()>0?GOLD:GREEN,true));Button refresh=btn("ATUALIZAR PREÇOS PRÓXIMOS",false);add(strip,refresh,0,8,0,0,-1,dp(50));refresh.setOnClickListener(v->refresh(false));add(page,strip,0,0,0,14,-1,-2);
        page.addView(over("MENORES PREÇOS PRÓXIMOS",MUTED));if(!Double.isFinite(lat)||!Double.isFinite(lon)){page.addView(text("GPS ainda não disponível.",12,MUTED,false));return;}ArrayList<FuelCommunityStore.Price> rows=store.cached(lat,lon);if(rows.isEmpty())page.addView(text("Nenhum preço comunitário em cache. Toque em atualizar.",12,MUTED,false));for(int i=0;i<Math.min(24,rows.size());i++){FuelCommunityStore.Price x=rows.get(i);LinearLayout c=card();LinearLayout line=row();TextView name=text(x.station,16,TEXT,true);line.addView(name,new LinearLayout.LayoutParams(0,-2,1));TextView value=text(String.format(Locale.getDefault(),"R$ %.2f",x.price),18,GREEN,true);line.addView(value);c.addView(line);String d=x.fuel; if(Double.isFinite(x.distanceM))d+=" · "+(x.distanceM>=1000?String.format(Locale.getDefault(),"%.1f km",x.distanceM/1000.0):Math.round(x.distanceM)+" m");if(x.at>0)d+=" · "+new SimpleDateFormat("dd/MM HH:mm",Locale.getDefault()).format(new Date(x.at));c.addView(text(d,11,MUTED,false));add(page,c,0,7,0,0,-1,-2);}
    }
    private void refresh(boolean afterReport){if(!Double.isFinite(lat)||!Double.isFinite(lon)){toast("Sem GPS válido.");return;}io.execute(()->{boolean ok=store.sync(new ApiClient(getApplicationContext()),lat,lon);runOnUiThread(()->{if(!afterReport)toast(ok?"Preços atualizados.":"Não consegui atualizar agora; mantendo o cache.");build();});});}
    private EditText field(String hint,boolean number){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setBackground(panel(SURFACE2,12,BORDER));e.setPadding(dp(12),0,dp(12),0);if(number)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(8),0,0);e.setLayoutParams(p);return e;}private LinearLayout card(){LinearLayout c=col();c.setPadding(dp(15),dp(14),dp(15),dp(14));c.setBackground(panel(SURFACE,16,BORDER));return c;}private Button btn(String v,boolean pri){Button b=new Button(this);b.setAllCaps(false);b.setText(v);b.setTextColor(TEXT);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(panel(pri?RED:SURFACE2,13,pri?0:BORDER));return b;}private TextView text(String v,float s,int c,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private TextView over(String v,int c){TextView t=text(v,9,c,true);t.setLetterSpacing(.12f);return t;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private GradientDrawable panel(int c,int r,int st){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(st!=0)g.setStroke(dp(1),st);return g;}private void add(LinearLayout p,View v,int l,int t,int r,int b,int w,int h){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(w,h);x.setMargins(dp(l),dp(t),dp(r),dp(b));p.addView(v,x);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
