package com.estradaplay.comunista;

import android.Manifest;import android.annotation.SuppressLint;import android.bluetooth.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;import java.util.regex.*;

@SuppressLint("MissingPermission") // OBD2_PERMISSION_GUARD_V300: every Bluetooth call is runtime-guarded and revocation races catch SecurityException.
public final class Obd2Activity extends ComponentActivity {
    private static final int REQ_BT=7301;private static final UUID SPP=UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");
    private final int BG=Color.rgb(8,5,7),SURFACE=Color.rgb(18,9,12),SURFACE2=Color.rgb(28,14,18),BORDER=Color.rgb(76,38,44),TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38),GREEN=Color.rgb(72,212,134),GOLD=Color.rgb(226,185,76);private final ExecutorService io=Executors.newSingleThreadExecutor();private final Handler ui=new Handler(Looper.getMainLooper());private LinearLayout page,devices;private TextView state,rpm,coolant,vehicleSpeed,battery,fuel;private BluetoothSocket socket;private InputStream in;private OutputStream out;private volatile boolean polling;
    @Override protected void onCreate(Bundle b){super.onCreate(b);build();}@Override protected void onDestroy(){polling=false;try{if(socket!=null)socket.close();}catch(Throwable ignored){}io.shutdownNow();super.onDestroy();}
    private void build(){ScrollView sv=new ScrollView(this);page=col();page.setPadding(dp(18),dp(16),dp(18),dp(28));page.setBackgroundColor(BG);sv.addView(page);setContentView(UnifiedAppShell.wrap(this,"central",sv));LinearLayout h=row();Button back=btn("‹ CENTRAL",false);h.addView(back,new LinearLayout.LayoutParams(dp(100),dp(46)));back.setOnClickListener(v->finish());LinearLayout tt=col();tt.addView(over("OBD2 BLUETOOTH",RED));tt.addView(text("Painel do veículo",27,TEXT,true));tt.addView(text("Compatível com adaptadores ELM327 Bluetooth Classic já pareados no Android.",11,MUTED,false));h.addView(tt,new LinearLayout.LayoutParams(0,-2,1));page.addView(h);
        LinearLayout status=card();state=text("DESCONECTADO",13,GOLD,true);status.addView(state);status.addView(text("Pareie primeiro o ELM327 nas configurações Bluetooth do aparelho. O Estrada Play não altera parâmetros da ECU; apenas consulta PIDs padrão.",11,MUTED,false));add(page,status,0,14,0,14,-1,-2);
        LinearLayout metrics=row();rpm=metric("RPM","--");coolant=metric("MOTOR °C","--");metrics.addView(rpm,new LinearLayout.LayoutParams(0,dp(88),1));LinearLayout.LayoutParams m2=new LinearLayout.LayoutParams(0,dp(88),1);m2.setMargins(dp(7),0,0,0);metrics.addView(coolant,m2);page.addView(metrics);LinearLayout metrics2=row();vehicleSpeed=metric("OBD KM/H","--");battery=metric("BATERIA","--");fuel=metric("TANQUE","--");metrics2.addView(vehicleSpeed,new LinearLayout.LayoutParams(0,dp(88),1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(0,dp(88),1);q.setMargins(dp(7),0,0,0);metrics2.addView(battery,q);LinearLayout.LayoutParams q2=new LinearLayout.LayoutParams(0,dp(88),1);q2.setMargins(dp(7),0,0,0);metrics2.addView(fuel,q2);add(page,metrics2,0,7,0,16,-1,-2);
        page.addView(over("DISPOSITIVOS PAREADOS",MUTED));devices=col();page.addView(devices);loadBonded();
    }
    private boolean hasBluetoothConnectPermission(){return Build.VERSION.SDK_INT<31||checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)==PackageManager.PERMISSION_GRANTED;}
    private void loadBonded(){devices.removeAllViews();if(!hasBluetoothConnectPermission()){Button allow=btn("AUTORIZAR BLUETOOTH",true);devices.addView(allow,new LinearLayout.LayoutParams(-1,dp(54)));allow.setOnClickListener(v->requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT},REQ_BT));return;}BluetoothAdapter a=BluetoothAdapter.getDefaultAdapter();if(a==null){devices.addView(text("Este aparelho não possui Bluetooth Classic.",12,MUTED,false));return;}try{if(!a.isEnabled()){devices.addView(text("Ative o Bluetooth do Android e volte a esta tela.",12,GOLD,false));return;}}catch(SecurityException e){devices.addView(text("Autorize o Bluetooth para continuar.",12,GOLD,false));return;}Set<BluetoothDevice> set;try{set=a.getBondedDevices();}catch(SecurityException e){devices.addView(text("Autorize o Bluetooth para ler os dispositivos pareados.",12,MUTED,false));return;}catch(Throwable e){devices.addView(text("Não consegui ler os dispositivos pareados.",12,MUTED,false));return;}if(set==null||set.isEmpty()){devices.addView(text("Nenhum dispositivo pareado. Pareie o ELM327 nas configurações do Android.",12,MUTED,false));return;}for(BluetoothDevice d:set){String name=safeName(d);Button b=btn(name+"\n"+safeAddress(d),false);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);devices.addView(b,new LinearLayout.LayoutParams(-1,dp(62)));final BluetoothDevice device=d;b.setOnClickListener(v->connect(device));}}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_BT)loadBonded();}
    private String safeAddress(BluetoothDevice d){if(d==null||!hasBluetoothConnectPermission())return "";try{return d.getAddress();}catch(SecurityException e){return "";}catch(Throwable e){return "";}}
    private void connect(BluetoothDevice d){if(polling||d==null)return;if(!hasBluetoothConnectPermission()){requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT},REQ_BT);return;}state.setText("CONECTANDO…");io.execute(()->{if(!hasBluetoothConnectPermission()){ui.post(()->state.setText("AUTORIZE O BLUETOOTH PARA CONECTAR"));return;}try{BluetoothAdapter a=BluetoothAdapter.getDefaultAdapter();if(a!=null)a.cancelDiscovery();socket=d.createRfcommSocketToServiceRecord(SPP);socket.connect();in=socket.getInputStream();out=socket.getOutputStream();initElm();polling=true;ui.post(()->state.setText("CONECTADO · "+safeName(d)));pollLoop();}catch(SecurityException e){polling=false;closeSocket();ui.post(()->state.setText("AUTORIZE O BLUETOOTH PARA CONECTAR"));}catch(Throwable e){polling=false;closeSocket();ui.post(()->state.setText("FALHA AO CONECTAR · verifique se o ELM327 está livre"));}});}
    private String safeName(BluetoothDevice d){if(d==null||!hasBluetoothConnectPermission())return "ELM327";try{String n=d.getName();return n==null||n.trim().isEmpty()?"Dispositivo Bluetooth":n;}catch(SecurityException e){return "ELM327";}catch(Throwable e){return "ELM327";}}
    private void initElm()throws Exception{command("ATZ",3000);command("ATE0",1200);command("ATL0",1200);command("ATS0",1200);command("ATH0",1200);command("ATSP0",2200);}
    private void pollLoop(){while(polling&&!Thread.currentThread().isInterrupted()){try{Double r=parsePid(command("010C",1400),"410C",2,4.0);Double c=parsePid(command("0105",1400),"4105",1,1.0);Double s=parsePid(command("010D",1400),"410D",1,1.0);Double f=parsePid(command("012F",1400),"412F",1,255.0/100.0);Double volts=parseVoltage(command("ATRV",1400));ui.post(()->{if(r!=null)rpm.setText(String.valueOf(Math.round(r)));if(c!=null)coolant.setText(String.valueOf(Math.round(c-40)));if(s!=null)vehicleSpeed.setText(String.valueOf(Math.round(s)));if(volts!=null)battery.setText(String.format(Locale.getDefault(),"%.1f V",volts));if(f!=null)fuel.setText(Math.round(f)+"%");});Thread.sleep(900);}catch(Throwable e){polling=false;closeSocket();ui.post(()->state.setText("CONEXÃO OBD ENCERRADA"));}}}
    private synchronized String command(String cmd,long timeout)throws Exception{if(out==null||in==null)throw new IOException("sem conexão");while(in.available()>0)in.read();out.write((cmd+"\r").getBytes(StandardCharsets.US_ASCII));out.flush();long end=System.currentTimeMillis()+timeout;ByteArrayOutputStream b=new ByteArrayOutputStream();while(System.currentTimeMillis()<end){int n=in.available();if(n>0){byte[]buf=new byte[Math.min(256,n)];int x=in.read(buf);if(x>0){b.write(buf,0,x);String t=b.toString("US-ASCII");if(t.contains(">"))break;}}else Thread.sleep(35);}return b.toString("US-ASCII");}
    private Double parsePid(String raw,String marker,int bytes,double divisor){if(raw==null)return null;String x=raw.toUpperCase(Locale.ROOT).replaceAll("[^0-9A-F]","");int at=x.indexOf(marker);if(at<0)return null;int start=at+marker.length();if(x.length()<start+bytes*2)return null;try{if(bytes==1){int a=Integer.parseInt(x.substring(start,start+2),16);return divisor==1.0?(double)a:a/divisor;}int a=Integer.parseInt(x.substring(start,start+2),16),b=Integer.parseInt(x.substring(start+2,start+4),16);return (a*256.0+b)/divisor;}catch(Throwable e){return null;}}
    private Double parseVoltage(String raw){if(raw==null)return null;Matcher m=Pattern.compile("([0-9]{1,2}(?:\\.[0-9]+)?)\\s*V",Pattern.CASE_INSENSITIVE).matcher(raw);if(!m.find())return null;try{return Double.parseDouble(m.group(1));}catch(Throwable e){return null;}}
    private void closeSocket(){try{if(socket!=null)socket.close();}catch(Throwable ignored){}socket=null;in=null;out=null;}
    private TextView metric(String k,String v){TextView t=text(v+"\n"+k,18,GREEN,true);t.setGravity(Gravity.CENTER);t.setBackground(panel(SURFACE,15,BORDER));return t;}private LinearLayout card(){LinearLayout c=col();c.setPadding(dp(15),dp(14),dp(15),dp(14));c.setBackground(panel(SURFACE,16,BORDER));return c;}private Button btn(String v,boolean pri){Button b=new Button(this);b.setAllCaps(false);b.setText(v);b.setTextColor(TEXT);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(panel(pri?RED:SURFACE2,13,pri?0:BORDER));return b;}private TextView text(String v,float s,int c,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private TextView over(String v,int c){TextView t=text(v,9,c,true);t.setLetterSpacing(.12f);return t;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private GradientDrawable panel(int c,int r,int st){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(st!=0)g.setStroke(dp(1),st);return g;}private void add(LinearLayout p,View v,int l,int t,int r,int b,int w,int h){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(w,h);x.setMargins(dp(l),dp(t),dp(r),dp(b));p.addView(v,x);}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
