package com.estradaplay.comunista;
import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import org.json.*;import java.util.*;
public final class RoadReportActivity extends ComponentActivity{
    private static final String P="epc_road_reports_v140";private LinearLayout page;private String selected="";private double lat=Double.NaN,lon=Double.NaN;private BroadcastReceiver rx;private boolean reg;
    @Override protected void onCreate(Bundle b){super.onCreate(b);build();}
    private void build(){page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(20),dp(22),dp(20),dp(24));page.setBackgroundColor(Color.rgb(9,5,7));setContentView(page);TextView h=t("REPORTAR PONTO",27,Color.rgb(246,238,224),true);page.addView(h);page.addView(t("Faça o reporte somente quando for seguro tocar no aparelho. A contribuição fica pendente até o servidor aceitar.",13,Color.rgb(174,151,146),false));for(String[] x:new String[][]{{"RADAR_NOVO","RADAR NOVO"},{"RADAR_REMOVIDO","RADAR REMOVIDO"},{"LIMITE_ERRADO","LIMITE ERRADO"},{"QUEBRA_MOLAS","QUEBRA-MOLAS"},{"CAMERA_MONITORAMENTO","CÂMERA DE MONITORAMENTO"}})addOption(x[0],x[1]);Button send=new Button(this);send.setText("SALVAR REPORTE");send.setOnClickListener(v->save());page.addView(send,new LinearLayout.LayoutParams(-1,dp(58)));}
    private void addOption(String key,String label){Button b=new Button(this);b.setText(label);b.setOnClickListener(v->{selected=key;Toast.makeText(this,"Selecionado: "+label,Toast.LENGTH_SHORT).show();});page.addView(b,new LinearLayout.LayoutParams(-1,dp(50)));}
    @Override protected void onStart(){super.onStart();rx=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){lat=i.getDoubleExtra("lat",Double.NaN);lon=i.getDoubleExtra("lon",Double.NaN);}};IntentFilter f=new IntentFilter(RoadSafetyService.ACTION_STATE);if(Build.VERSION.SDK_INT>=33)registerReceiver(rx,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(rx,f);reg=true;}
    @Override protected void onStop(){if(reg){try{unregisterReceiver(rx);}catch(Throwable ignored){}reg=false;}super.onStop();}
    private void save(){if(selected.isEmpty()){Toast.makeText(this,"Escolha o tipo do reporte.",Toast.LENGTH_SHORT).show();return;}if(!Double.isFinite(lat)||!Double.isFinite(lon)){Toast.makeText(this,"Aguarde uma posição GPS válida.",Toast.LENGTH_SHORT).show();return;}try{JSONObject r=new JSONObject();r.put("type",selected);r.put("lat",lat);r.put("lon",lon);r.put("created_at",System.currentTimeMillis());SharedPreferences p=getSharedPreferences(P,MODE_PRIVATE);JSONArray q=new JSONArray(p.getString("queue","[]"));q.put(r);p.edit().putString("queue",q.toString()).apply();new Thread(()->uploadQueue(p),"epc-report").start();Toast.makeText(this,"Reporte salvo. Obrigado.",Toast.LENGTH_LONG).show();finish();}catch(Throwable e){Toast.makeText(this,"Não foi possível salvar.",Toast.LENGTH_SHORT).show();}}
    private void uploadQueue(SharedPreferences p){try{JSONArray q=new JSONArray(p.getString("queue","[]"));if(q.length()==0)return;ApiClient api=new ApiClient(this);JSONArray keep=new JSONArray();for(int i=0;i<q.length();i++){JSONObject r=q.optJSONObject(i);if(r==null)continue;try{ApiClient.Response x=api.post("api/road_reports.php",r);if(!x.ok()||!x.json().optBoolean("ok",false))keep.put(r);}catch(Throwable e){keep.put(r);}}p.edit().putString("queue",keep.toString()).apply();}catch(Throwable ignored){}}
    private TextView t(String v,float s,int c,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
