package com.estradaplay.comunista;
import android.content.Context;import android.content.Intent;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.Gravity;import android.view.View;import android.widget.FrameLayout;import android.widget.LinearLayout;import android.widget.TextView;import java.util.Locale;
// ALERT_CARD_V201: compact automotive alert that never blocks the whole map.
final class SafetyAlertOverlay{
 private static final String TAG="epc-v201-alert";private static String lastId="";private static long lastAt;private SafetyAlertOverlay(){}
 static void show(Context c,FrameLayout host,Intent i){if(c==null||host==null||i==null)return;String type=norm(i.getStringExtra("hazard_type"));if(!supported(type))return;String id=safe(i.getStringExtra("hazard_id"));if(id.isEmpty())id=type+":"+Math.round(i.getDoubleExtra("distance_m",0));long now=System.currentTimeMillis();if(id.equals(lastId)&&now-lastAt<9000)return;lastId=id;lastAt=now;View old=host.findViewWithTag(TAG);if(old!=null)host.removeView(old);
  int accent=color(type);LinearLayout card=new LinearLayout(c);card.setTag(TAG);card.setOrientation(LinearLayout.HORIZONTAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(c,14),dp(c,10),dp(c,14),dp(c,10));card.setBackground(round(Color.argb(247,20,8,11),17,accent,2));card.setClickable(true);if(android.os.Build.VERSION.SDK_INT>=21)card.setElevation(dp(c,52));
  TextView icon=text(c,icon(type),24,accent,true);icon.setGravity(Gravity.CENTER);card.addView(icon,new LinearLayout.LayoutParams(dp(c,46),dp(c,50)));
  LinearLayout meta=new LinearLayout(c);meta.setOrientation(LinearLayout.VERTICAL);TextView over=text(c,title(type),9,accent,true);over.setLetterSpacing(.11f);meta.addView(over);double d=i.getDoubleExtra("distance_m",0);String road=safe(i.getStringExtra("road"));int limit=i.getIntExtra("radar_limit_kmh",i.getIntExtra("limit_kmh",0));String main=d>0?distance(d):"À FRENTE";if("RADAR".equals(type)&&limit>0)main+="  ·  "+limit+" km/h";TextView big=text(c,main,18,Color.rgb(249,239,221),true);meta.addView(big);if(!road.isEmpty()){TextView r=text(c,road,10,Color.rgb(181,154,149),false);r.setMaxLines(1);meta.addView(r);}card.addView(meta,new LinearLayout.LayoutParams(0,-2,1));
  int delta=i.getIntExtra("overspeed_delta_kmh",0);if(delta>=2&&"RADAR".equals(type)){TextView red=text(c,"REDUZA\n"+delta+" acima",9,Color.WHITE,true);red.setGravity(Gravity.CENTER);red.setBackground(round(accent,12,0,0));red.setPadding(dp(c,8),dp(c,5),dp(c,8),dp(c,5));card.addView(red,new LinearLayout.LayoutParams(dp(c,76),dp(c,48)));}
  int sw=c.getResources().getDisplayMetrics().widthPixels;int width=Math.min(dp(c,420),Math.max(dp(c,270),sw-dp(c,28)));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(width,-2,Gravity.TOP|Gravity.CENTER_HORIZONTAL);lp.setMargins(0,dp(c,112),0,0);host.addView(card,lp);card.setAlpha(0f);card.setTranslationY(-dp(c,18));card.animate().alpha(1f).translationY(0).setDuration(170).start();card.setOnClickListener(v->dismiss(host,card));card.postDelayed(()->dismiss(host,card),i.getIntExtra("alert_level",1)>=2?5200L:4200L);
 }
 private static boolean supported(String t){return"RADAR".equals(t)||"QUEBRA_MOLAS".equals(t)||"CAMERA_MONITORAMENTO".equals(t)||"SEMAFORO".equals(t)||"PEDAGIO".equals(t)||"PASSAGEM_NIVEL".equals(t);}
 private static int color(String t){if("RADAR".equals(t))return Color.rgb(239,41,58);if("QUEBRA_MOLAS".equals(t))return Color.rgb(230,155,48);if("CAMERA_MONITORAMENTO".equals(t))return Color.rgb(226,185,76);if("SEMAFORO".equals(t))return Color.rgb(255,94,80);if("PEDAGIO".equals(t))return Color.rgb(72,205,134);return Color.rgb(230,155,48);}
 private static String icon(String t){if("RADAR".equals(t))return"◎";if("QUEBRA_MOLAS".equals(t))return"⌁";if("CAMERA_MONITORAMENTO".equals(t))return"◉";if("SEMAFORO".equals(t))return"●";if("PEDAGIO".equals(t))return"$";return"!";}
 private static String title(String t){if("RADAR".equals(t))return"RADAR À FRENTE";if("QUEBRA_MOLAS".equals(t))return"QUEBRA-MOLAS À FRENTE";if("CAMERA_MONITORAMENTO".equals(t))return"CÂMERA À FRENTE";if("SEMAFORO".equals(t))return"SEMÁFORO À FRENTE";if("PEDAGIO".equals(t))return"PEDÁGIO À FRENTE";return"PASSAGEM DE NÍVEL";}
 private static String distance(double d){return d>=1000?String.format(Locale.getDefault(),"%.1f km",d/1000.0):Math.max(10,Math.round(d/10.0)*10)+" m";}
 private static void dismiss(FrameLayout h,View v){if(v==null||v.getParent()==null)return;v.animate().alpha(0).translationY(-12).setDuration(140).withEndAction(()->{try{if(v.getParent()==h)h.removeView(v);}catch(Throwable ignored){}}).start();}
 private static String norm(String raw){String t=safe(raw).toUpperCase(Locale.ROOT).replace('-','_').replace(' ','_');if(t.contains("QUEBRA")||t.contains("LOMBADA")||t.contains("BUMP"))return"QUEBRA_MOLAS";if(t.contains("CAMERA")||t.contains("CÂMERA")||t.contains("MONITOR"))return"CAMERA_MONITORAMENTO";if(t.contains("RADAR")||t.contains("SPEED_CAMERA"))return"RADAR";if(t.contains("SEMAFOR"))return"SEMAFORO";if(t.contains("PEDAG"))return"PEDAGIO";if(t.contains("NIVEL")||t.contains("NÍVEL"))return"PASSAGEM_NIVEL";return t;}
 private static TextView text(Context c,String v,float s,int color,boolean bold){TextView t=new TextView(c);t.setText(v);t.setTextSize(s);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 private static GradientDrawable round(int color,int radius,int stroke,int sw){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius*density);if(stroke!=0&&sw>0)g.setStroke(Math.max(1,Math.round(sw*density)),stroke);return g;}private static float density=1f;private static int dp(Context c,float v){density=c.getResources().getDisplayMetrics().density;return Math.round(v*density);}private static String safe(String s){return s==null?"":s.trim();}
}
