package com.estradaplay.comunista;

import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import org.json.*;import java.util.*;import java.util.concurrent.*;

public final class TripPlannerActivity extends ComponentActivity{
    private final int BG=Color.rgb(8,5,7),SURFACE=Color.rgb(18,9,12),SURFACE2=Color.rgb(28,14,18),BORDER=Color.rgb(76,38,44),TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38),GREEN=Color.rgb(72,212,134),GOLD=Color.rgb(226,185,76);private LinearLayout page,result;private final ExecutorService io=Executors.newSingleThreadExecutor();private DestinationStore.Destination destination;
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);build();}@Override protected void onResume(){super.onResume();DestinationStore.Destination fresh=DestinationStore.read(this);if(!DestinationStore.same(destination,fresh)){build();}}@Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
    private void build(){destination=DestinationStore.read(this);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setOverScrollMode(View.OVER_SCROLL_NEVER);page=col();page.setPadding(dp(18),dp(16),dp(18),dp(28));page.setBackgroundColor(BG);sv.addView(page);setContentView(UnifiedAppShell.wrap(this,"trip",sv));
        LinearLayout head=row();head.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("‹ VOLTAR",false);head.addView(back,new LinearLayout.LayoutParams(dp(94),dp(46)));back.setOnClickListener(v->finish());LinearLayout title=col();title.addView(over("VIAGEM",RED));title.addView(text("Planejador",28,TEXT,true));head.addView(title,new LinearLayout.LayoutParams(0,-2,1));page.addView(head);
        LinearLayout dest=card();dest.addView(over(destination==null?"SEM DESTINO":"DESTINO",destination==null?MUTED:GREEN));TextView dt=text(destination==null?"Para onde você vai?":destination.label,21,TEXT,true);dt.setMaxLines(2);dest.addView(dt);dest.addView(text(destination==null?"Defina um destino para calcular distância, tempo, combustível e perigos conhecidos.":"Pronto para calcular o plano com sua posição atual.",11,MUTED,false));Button choose=btn(destination==null?"DEFINIR DESTINO":"MUDAR DESTINO",true);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(54));cp.setMargins(0,dp(14),0,0);dest.addView(choose,cp);choose.setOnClickListener(v->startActivity(new Intent(this,DestinationActivity.class)));LinearLayout.LayoutParams dpv=new LinearLayout.LayoutParams(-1,-2);dpv.setMargins(0,dp(14),0,0);page.addView(dest,dpv);
        LinearLayout actions=row();Button road=btn("SÓ ESTRADA",false);actions.addView(road,new LinearLayout.LayoutParams(0,dp(54),1));road.setOnClickListener(v->{DriveSettings.toggle(this,"only_road_mode",true);DestinationStore.clear(this);startActivity(new Intent(this,RoadMapActivity.class));finish();});if(destination!=null){Button calc=btn("CALCULAR PLANO",true);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(54),1);p.setMargins(dp(8),0,0,0);actions.addView(calc,p);calc.setOnClickListener(v->calculate(destination));}LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,-2);ap.setMargins(0,dp(10),0,0);page.addView(actions,ap);
        result=col();LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(16),0,0);page.addView(result,rp);renderHint();
    }
    private void renderHint(){result.removeAllViews();LinearLayout h=card();h.addView(over("ANTES DE SAIR",GOLD));h.addView(text("O plano usa sua rota, seu perfil de veículo e a base de segurança já disponível no aparelho.",13,TEXT,true));h.addView(text("Preço de pedágio só aparece quando houver uma fonte confiável; o app não inventa valores.",10,MUTED,false));result.addView(h);}
    private void calculate(DestinationStore.Destination d){if(DriveSettings.offlineTestMode(this)){toast("O cálculo de rota precisa de internet. Os alertas continuam offline.");return;}Location l=last();if(l==null){toast("Ainda não tenho uma posição GPS válida.");return;}result.removeAllViews();LinearLayout loading=card();loading.addView(over("CALCULANDO",RED));loading.addView(text("Montando seu plano de viagem…",18,TEXT,true));loading.addView(text("A análise acontece fora da tela para não travar o app.",10,MUTED,false));result.addView(loading);io.execute(()->{try{RouteEngine.Route r=RouteEngine.fetch(l.getLatitude(),l.getLongitude(),d.lat,d.lon);RoadPackStore store=new RoadPackStore(getApplicationContext());RoadQualityStore quality=new RoadQualityStore(getApplicationContext());Plan p=analyze(r,store,quality);runOnUiThread(()->showPlan(r,p,d));}catch(Throwable e){runOnUiThread(()->{result.removeAllViews();LinearLayout er=card();er.addView(over("ROTA INDISPONÍVEL",RED));er.addView(text("Não consegui calcular agora. Sua proteção de estrada continua funcionando.",13,TEXT,true));result.addView(er);});}});}
    private Plan analyze(RouteEngine.Route r,RoadPackStore store,RoadQualityStore quality){Plan p=new Plan();try{JSONObject root=new JSONObject(r.geoJson);JSONArray f=root.optJSONArray("features");JSONObject g=f==null?null:f.optJSONObject(0);JSONObject geo=g==null?null:g.optJSONObject("geometry");JSONArray coords=geo==null?null:geo.optJSONArray("coordinates");HashSet<String> ids=new HashSet<>();double score=0;int scoreN=0;if(coords!=null){int step=Math.max(1,coords.length()/55);for(int i=0;i<coords.length();i+=step){JSONArray c=coords.optJSONArray(i);if(c==null)continue;double lon=c.optDouble(0),lat=c.optDouble(1);for(RoadHazard h:store.nearby(lat,lon,500)){if(!ids.add(h.id))continue;if("RADAR".equals(h.type))p.radars++;else if("QUEBRA_MOLAS".equals(h.type))p.bumps++;else if("PEDAGIO".equals(h.type))p.tolls++;}score+=quality.scoreNear(lat,lon);scoreN++;}}p.quality=scoreN==0?100:(int)Math.round(score/scoreN);}catch(Throwable ignored){}return p;}
    private void showPlan(RouteEngine.Route r,Plan p,DestinationStore.Destination d){VehicleProfileStore.Profile v=VehicleProfileStore.active(this);double km=r.distanceM/1000.0,liters=km/Math.max(1f,v.kmL),cost=liters*v.fuelPrice;result.removeAllViews();LinearLayout ready=card();ready.addView(over("PLANO PRONTO",GREEN));ready.addView(text(d.label,19,TEXT,true));ready.addView(text(r.summary(),12,MUTED,false));LinearLayout metrics=row();metrics.addView(metric("COMBUSTÍVEL",String.format(Locale.getDefault(),"%.1f L",liters),GOLD),new LinearLayout.LayoutParams(0,dp(82),1));LinearLayout.LayoutParams c=new LinearLayout.LayoutParams(0,dp(82),1);c.setMargins(dp(8),0,0,0);metrics.addView(metric("CUSTO",v.fuelPrice>0?String.format(Locale.getDefault(),"R$ %.2f",cost):"—",GREEN),c);LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(0,dp(82),1);q.setMargins(dp(8),0,0,0);metrics.addView(metric("VIA",p.quality+"/100",RED),q);LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(-1,-2);mp.setMargins(0,dp(14),0,0);ready.addView(metrics,mp);ready.addView(text("Radares conhecidos na rota: "+p.radars+"   ·   Quebra-molas: "+p.bumps+"   ·   Pedágios detectados: "+p.tolls,11,TEXT,true));ready.addView(text("Valores de pedágio: indisponíveis sem fonte confiável.",10,MUTED,false));Button go=btn("INICIAR VIAGEM",true);LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(58));gp.setMargins(0,dp(16),0,0);ready.addView(go,gp);go.setOnClickListener(x->{DriveSettings.toggle(this,"only_road_mode",false);startActivity(new Intent(this,RoadMapActivity.class));finish();});result.addView(ready);}
    private View metric(String k,String v,int accent){LinearLayout m=col();m.setGravity(Gravity.CENTER);m.setBackground(panel(SURFACE2,14,BORDER));TextView vv=text(v,17,accent,true);vv.setGravity(Gravity.CENTER);m.addView(vv);TextView kk=over(k,MUTED);kk.setGravity(Gravity.CENTER);m.addView(kk);return m;}
    private Location last(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return null;try{LocationManager m=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;for(String p:new String[]{LocationManager.GPS_PROVIDER,LocationManager.NETWORK_PROVIDER}){Location x=m.getLastKnownLocation(p);if(x!=null&&(best==null||x.getTime()>best.getTime()))best=x;}return best;}catch(Throwable e){return null;}}
    private LinearLayout card(){LinearLayout c=col();c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(panel(SURFACE,17,BORDER));return c;}private Button btn(String v,boolean pri){Button b=new Button(this);b.setAllCaps(false);b.setText(v);b.setTextColor(TEXT);b.setTextSize(10);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setStateListAnimator(null);b.setBackground(panel(pri?RED:SURFACE2,14,pri?0:BORDER));return b;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private TextView text(String v,float s,int c,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);t.setGravity(Gravity.CENTER_VERTICAL);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private TextView over(String v,int c){TextView t=text(v,9,c,true);t.setLetterSpacing(.12f);return t;}private GradientDrawable panel(int c,int r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(stroke!=0)g.setStroke(dp(1),stroke);return g;}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private static final class Plan{int radars,bumps,tolls,quality=100;}
}
