package com.estradaplay.comunista;
import android.content.Context;
import android.content.SharedPreferences;
import android.location.Location;
import org.json.JSONArray;
import org.json.JSONObject;
final class TripRecorder {
    private static final String PREFS="epc_trip_history_v140",KEY_HISTORY="history",KEY_ACTIVE="active"; private static final long IDLE_FINISH_MS=5L*60L*1000L;
    private final Context app; private final SharedPreferences prefs; private JSONObject active; private Location last; private long lastMovingAt,lastPersistAt;
    TripRecorder(Context c){app=c.getApplicationContext();prefs=app.getSharedPreferences(PREFS,Context.MODE_PRIVATE);try{String raw=prefs.getString(KEY_ACTIVE,"");if(raw!=null&&!raw.isEmpty())active=new JSONObject(raw);}catch(Throwable ignored){active=null;}}
    synchronized void onLocation(Location loc,double speedKmh){if(loc==null)return;long now=System.currentTimeMillis();if(speedKmh>=4){if(active==null)start(now,loc);lastMovingAt=now;}else if(active!=null&&lastMovingAt>0&&now-lastMovingAt>=IDLE_FINISH_MS){finish("parada");last=new Location(loc);return;}if(active==null){last=new Location(loc);return;}try{double add=0;if(last!=null){float d=last.distanceTo(loc);if(d>=0&&d<=1500)add=d;}active.put("distance_m",active.optDouble("distance_m",0)+add);active.put("max_speed",Math.max(active.optDouble("max_speed",0),Math.max(0,speedKmh)));active.put("last_lat",loc.getLatitude());active.put("last_lon",loc.getLongitude());active.put("updated_at",now);if(now-lastPersistAt>=12000)persistActive();}catch(Throwable ignored){}last=new Location(loc);}
    synchronized void onHazard(String type){if(active==null)return;try{if("RADAR".equals(type))active.put("radars",active.optInt("radars",0)+1);else if("QUEBRA_MOLAS".equals(type))active.put("bumps",active.optInt("bumps",0)+1);else if("CAMERA_MONITORAMENTO".equals(type))active.put("cameras",active.optInt("cameras",0)+1);else active.put("other_alerts",active.optInt("other_alerts",0)+1);addTimeline(type,type,System.currentTimeMillis(),active.optDouble("last_lat",0),active.optDouble("last_lon",0),0);persistActive();}catch(Throwable ignored){}}
    synchronized void onRoadImpact(RoadSurfaceMonitor.Impact x){if(active==null||x==null)return;try{active.put("road_impacts",active.optInt("road_impacts",0)+1);active.put("roughness_sum",active.optDouble("roughness_sum",0)+x.force);addTimeline("VIA_IRREGULAR","Impacto/irregularidade",x.at,x.lat,x.lon,x.force);persistActive();}catch(Throwable ignored){}}
    synchronized void onRestSuggested(){if(active==null)return;try{addTimeline("PAUSA","Pausa sugerida",System.currentTimeMillis(),active.optDouble("last_lat",0),active.optDouble("last_lon",0),0);persistActive();}catch(Throwable ignored){}}
    synchronized void finish(String reason){if(active==null)return;try{long now=System.currentTimeMillis();active.put("ended_at",now);active.put("duration_ms",Math.max(0,now-active.optLong("started_at",now)));active.put("reason",reason==null?"":reason);double km=active.optDouble("distance_m",0)/1000.0;double liters=km/DriveSettings.consumptionKml(app);active.put("fuel_l",liters);active.put("fuel_cost",liters*DriveSettings.fuelPrice(app));int impacts=active.optInt("road_impacts",0);double score=Math.max(1,Math.min(100,100-(impacts*120.0/Math.max(5.0,km))));active.put("road_quality_score",Math.round(score));JSONArray old=history(prefs),out=new JSONArray();out.put(active);for(int i=0;i<old.length()&&out.length()<30;i++)out.put(old.opt(i));prefs.edit().putString(KEY_HISTORY,out.toString()).remove(KEY_ACTIVE).apply();}catch(Throwable ignored){}active=null;last=null;lastMovingAt=0;}
    private void start(long now,Location loc){active=new JSONObject();try{active.put("started_at",now);active.put("updated_at",now);active.put("start_lat",loc.getLatitude());active.put("start_lon",loc.getLongitude());active.put("distance_m",0);active.put("max_speed",0);active.put("radars",0);active.put("bumps",0);active.put("cameras",0);active.put("other_alerts",0);active.put("road_impacts",0);active.put("timeline",new JSONArray());addTimeline("SAIDA","Viagem iniciada",now,loc.getLatitude(),loc.getLongitude(),0);}catch(Throwable ignored){}lastMovingAt=now;persistActive();}
    private void addTimeline(String type,String label,long at,double lat,double lon,double value){try{JSONArray a=active.optJSONArray("timeline");if(a==null)a=new JSONArray();JSONObject e=new JSONObject();e.put("type",type);e.put("label",label);e.put("at",at);e.put("lat",lat);e.put("lon",lon);if(value>0)e.put("value",value);JSONArray out=new JSONArray();int start=Math.max(0,a.length()-38);for(int i=start;i<a.length();i++)out.put(a.opt(i));out.put(e);active.put("timeline",out);}catch(Throwable ignored){}}
    private void persistActive(){lastPersistAt=System.currentTimeMillis();if(active!=null)prefs.edit().putString(KEY_ACTIVE,active.toString()).apply();}
    static JSONArray history(Context c){return history(c.getSharedPreferences(PREFS,Context.MODE_PRIVATE));}private static JSONArray history(SharedPreferences p){try{return new JSONArray(p.getString(KEY_HISTORY,"[]"));}catch(Throwable ignored){return new JSONArray();}}
    static void clear(Context c){c.getSharedPreferences(PREFS,Context.MODE_PRIVATE).edit().remove(KEY_HISTORY).apply();}
}
