package com.estradaplay.comunista;
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.os.*;import android.speech.*;import android.speech.tts.TextToSpeech;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import java.util.*;
public final class VoiceCommandActivity extends ComponentActivity implements RecognitionListener{
    private static final int REQ=2201;private SpeechRecognizer sr;private TextToSpeech tts;private TextView state;private int lastLimit;private String lastHazard="";private double lastDistance;private boolean reg;private BroadcastReceiver rx;
    @Override protected void onCreate(Bundle b){super.onCreate(b);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setGravity(Gravity.CENTER);p.setPadding(dp(24),dp(24),dp(24),dp(24));p.setBackgroundColor(Color.rgb(9,5,7));setContentView(p);TextView title=t("COMANDO DE VOZ",28,Color.rgb(246,238,224),true);p.addView(title);TextView hint=t("Exemplos: ‘qual o limite’, ‘tem radar’, ‘abrir câmera’, ‘posto’, ‘histórico’, ‘HUD’, ‘reportar’, ‘definir destino’. O microfone só é usado enquanto esta tela escuta.",13,Color.rgb(174,151,146),false);hint.setGravity(Gravity.CENTER);p.addView(hint);state=t("TOQUE PARA FALAR",16,Color.rgb(224,184,76),true);state.setGravity(Gravity.CENTER);p.addView(state);Button speak=new Button(this);speak.setText("FALAR");speak.setOnClickListener(v->listen());p.addView(speak,new LinearLayout.LayoutParams(-1,dp(62)));tts=new TextToSpeech(this,x->{if(x==TextToSpeech.SUCCESS)tts.setLanguage(new Locale("pt","BR"));});}
    private void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ);return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){say("Reconhecimento de voz não está disponível neste aparelho.");return;}if(sr==null){sr=SpeechRecognizer.createSpeechRecognizer(this);sr.setRecognitionListener(this);}Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"pt-BR");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,3);state.setText("OUVINDO...");sr.startListening(i);}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)listen();}
    @Override public void onResults(Bundle b){ArrayList<String> a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);String q=a==null||a.isEmpty()?"":a.get(0).toLowerCase(Locale.ROOT);state.setText(q.isEmpty()?"NÃO ENTENDI":q.toUpperCase(Locale.ROOT));handle(q);}
    private void handle(String q){if(q.contains("limite")){say(lastLimit>0?"O limite registrado aqui é "+lastLimit+" quilômetros por hora.":"Ainda não tenho um limite confirmado para esta via.");return;}if(q.contains("radar")){say(lastHazard.toLowerCase(Locale.ROOT).contains("radar")?"Há radar detectado a aproximadamente "+Math.round(lastDistance)+" metros.":"Não há radar dentro da janela de alerta atual.");return;}if(q.contains("câmera")||q.contains("camera")){open(CameraActivity.class);return;}if(q.contains("posto")||q.contains("hospital")||q.contains("oficina")||q.contains("restaurante")){open(NearbyServicesActivity.class);return;}if(q.contains("histórico")||q.contains("historico")){open(TripHistoryActivity.class);return;}if(q.contains("hud")){open(HudActivity.class);return;}if(q.contains("report")){open(RoadReportActivity.class);return;}if(q.contains("destino")||q.contains("endereço")||q.contains("endereco")){open(DestinationActivity.class);return;}say("Comando não reconhecido ainda.");}
    private void open(Class<?> c){startActivity(new Intent(this,c));}
    private void say(String v){state.setText(v);try{if(tts!=null)tts.speak(v,TextToSpeech.QUEUE_FLUSH,null,"epc-command");}catch(Throwable ignored){}}
    @Override protected void onStart(){super.onStart();rx=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){lastLimit=i.getIntExtra("road_limit_kmh",0);String h=i.getStringExtra("hazard_label");if(h!=null&&!h.isEmpty()){lastHazard=h;lastDistance=i.getDoubleExtra("distance_m",0);}}};IntentFilter f=new IntentFilter(RoadSafetyService.ACTION_STATE);if(Build.VERSION.SDK_INT>=33)registerReceiver(rx,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(rx,f);reg=true;}
    @Override protected void onStop(){if(reg)try{unregisterReceiver(rx);}catch(Throwable ignored){}reg=false;super.onStop();}
    @Override protected void onDestroy(){try{if(sr!=null)sr.destroy();}catch(Throwable ignored){}try{if(tts!=null){tts.stop();tts.shutdown();}}catch(Throwable ignored){}super.onDestroy();}
    @Override public void onReadyForSpeech(Bundle p){}@Override public void onBeginningOfSpeech(){}@Override public void onRmsChanged(float r){}@Override public void onBufferReceived(byte[] b){}@Override public void onEndOfSpeech(){}@Override public void onError(int e){state.setText("TOQUE PARA TENTAR NOVAMENTE");}@Override public void onPartialResults(Bundle b){}@Override public void onEvent(int e,Bundle b){}
    private TextView t(String v,float s,int c,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
