<?php
require_once __DIR__.'/../api/bootstrap.php';require_login();$m=current_medico();$err='';$aid=(int)($_GET['atendimento_id']??0);
$s=db()->prepare('SELECT id,nome FROM pacientes WHERE medico_id=? ORDER BY nome');$s->execute([$m['id']]);$ps=$s->fetchAll();
$models=db()->prepare("SELECT id,nome,conteudo FROM modelos_documento WHERE medico_id=? AND tipo='LAUDO' AND ativo=1 ORDER BY nome");$models->execute([$m['id']]);$models=$models->fetchAll();
$pre=[];$selectedPatient=(int)($_GET['paciente_id']??0);if($aid){$s=db()->prepare('SELECT * FROM atendimentos WHERE id=? AND medico_id=?');$s->execute([$aid,$m['id']]);$pre=$s->fetch()?:[];$selectedPatient=(int)($pre['paciente_id']??$selectedPatient);}
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$pid=(int)($_POST['paciente_id']??0);$p=patient_for_doctor($pid,$m['id']);$v=[];foreach(['titulo','historico_clinico','avaliacao','exames','cid_codigo','cid_descricao','atividade_habitual','repercussao','periodo_estimado','incapacidade_restricao','conclusao','conteudo_personalizado'] as $f)$v[$f]=trim($_POST[$f]??'');$mid=(int)($_POST['modelo_id']??0);
if(!$p)$err='Paciente inválido.';elseif($v['conclusao']==='')$err='A conclusão é obrigatória.';elseif(empty($_POST['confirmar']))$err='Confirme a revisão médica.';
else{$code=unique_code('LAUD');$q=db()->prepare('INSERT INTO laudos(paciente_id,medico_id,atendimento_id,codigo_validacao,data_emissao,titulo,conteudo_personalizado,historico_clinico,avaliacao,exames,cid_codigo,cid_descricao,atividade_habitual,repercussao,periodo_estimado,incapacidade_restricao,modelo_id,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$pid,$m['id'],$aid?:null,$code,date('Y-m-d H:i:s'),$v['titulo']?:'Laudo Médico',$v['conteudo_personalizado'],$v['historico_clinico'],$v['avaliacao'],$v['exames'],$v['cid_codigo'],$v['cid_descricao'],$v['atividade_habitual'],$v['repercussao'],$v['periodo_estimado'],$v['incapacidade_restricao'],$mid?:null,'EMITIDO']);$id=db()->lastInsertId();db()->prepare('INSERT INTO documentos_versoes(tipo,documento_id,medico_id,versao,conteudo) VALUES(?,?,?,?,?)')->execute(['LAUDO',$id,$m['id'],1,$v['conteudo_personalizado']]);audit_log('emitir_laudo','laudos',$id,['codigo'=>$code,'modelo_id'=>$mid]);header('Location:view.php?id='.$id);exit;}}
render_header('Novo laudo');?><h1>Laudo médico</h1><?php if($err):?><div class="error"><?=e($err)?></div><?php endif;?>
<form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>">
<div class="card"><div class="grid"><div><label>Paciente *</label><select name="paciente_id" required><option value="">Selecione</option><?php foreach($ps as $p):?><option value="<?=$p['id']?>" <?=$selectedPatient===$p['id']?'selected':''?>><?=e($p['nome'])?></option><?php endforeach;?></select></div><div><label>Modelo</label><select id="modelo" name="modelo_id"><option value="">Sem modelo</option><?php foreach($models as $x):?><option value="<?=$x['id']?>" data-text="<?=e($x['conteudo'])?>"><?=e($x['nome'])?></option><?php endforeach;?></select></div><div><label>Título</label><input name="titulo" value="Laudo Médico"></div><div><label>Atividade habitual</label><input name="atividade_habitual"></div><div><label>Período estimado</label><input name="periodo_estimado"></div></div></div>
<?php foreach([['historico_clinico','História clínica',$pre['historia_clinica']??''],['avaliacao','Avaliação / exame físico',$pre['exame_fisico']??''],['exames','Exames complementares',$pre['exames_apresentados']??''],['repercussao','Repercussão funcional',$pre['capacidade_impacto']??''],['incapacidade_restricao','Incapacidade/restrições',$pre['capacidade_restricoes']??''],['conclusao','Conclusão médica','']] as $f):?><div class="card"><label><?=e($f[1])?></label><textarea name="<?=e($f[0])?>" <?=($f[0]==='conclusao'?'required':'')?>><?=e($f[2])?></textarea></div><?php endforeach;?>
<div class="card"><h2>CID-10</h2><div class="grid"><div><label>Código</label><input id="cc" name="cid_codigo"><div id="cr" class="cid-results"></div></div><div><label>Descrição</label><input id="cd" name="cid_descricao"></div></div></div>
<div class="card"><label>Texto personalizado</label><textarea id="texto" name="conteudo_personalizado" rows="12"></textarea></div><div class="card"><label><input type="checkbox" name="confirmar" value="1" required> Revisei conteúdo, diagnóstico/CID e conclusão. Autorizo a emissão e assinatura.</label></div><button class="btn ok">Assinar e emitir</button></form>
<script>
const modelo=document.getElementById('modelo'),texto=document.getElementById('texto');modelo.onchange=()=>{const o=modelo.selectedOptions[0];if(o&&o.dataset.text)texto.value=o.dataset.text;};
const c=document.getElementById('cc'),d=document.getElementById('cd'),r=document.getElementById('cr');let t;c.oninput=()=>{clearTimeout(t);if(c.value.length<2){r.innerHTML='';return}t=setTimeout(()=>fetch('<?=e(medical_url('cid/search.php'))?>?q='+encodeURIComponent(c.value)).then(x=>x.json()).then(a=>r.innerHTML=a.map(x=>'<button type="button" data-c="'+x.codigo.replaceAll('"','&quot;')+'" data-d="'+x.descricao.replaceAll('"','&quot;')+'"><b>'+x.codigo+'</b> — '+x.descricao+'</button>').join('')).then(()=>r.querySelectorAll('button').forEach(b=>b.onclick=()=>{c.value=b.dataset.c;d.value=b.dataset.d;r.innerHTML='';})),250)};
</script><?php render_footer();