#!/usr/bin/env python3
from pathlib import Path
ROOT=Path('estrada-play-comunista-app')
if not ROOT.exists(): raise SystemExit('estrada-play-comunista-app not generated')
def read(r): return (ROOT/r).read_text(encoding='utf-8')
def write(r,v): p=ROOT/r;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(v,encoding='utf-8')

def rep(s,a,b,label):
    if a not in s: raise SystemExit('missing anchor '+label)
    return s.replace(a,b,1)

manifest=read('app/src/main/AndroidManifest.xml')
if 'android.permission.RECORD_AUDIO' not in manifest:
    manifest=rep(manifest,'    <uses-permission android:name="android.permission.CAMERA" />','    <uses-permission android:name="android.permission.CAMERA" />\n    <uses-permission android:name="android.permission.RECORD_AUDIO" />','mic permission')
if '.NearbyServicesActivity' not in manifest:
    block='''        <activity
            android:name=".NearbyServicesActivity"
            android:exported="false"
            android:screenOrientation="${appOrientation}" />

        <activity
            android:name=".VoiceCommandActivity"
            android:exported="false"
            android:screenOrientation="${appOrientation}" />

'''
    manifest=rep(manifest,'        <activity\n            android:name=".DriveToolsActivity"',block+'        <activity\n            android:name=".DriveToolsActivity"','extra activities')
write('app/src/main/AndroidManifest.xml',manifest)

write('app/src/main/java/com/estradaplay/comunista/NearbyServicesActivity.java',r'''package com.estradaplay.comunista;
import android.content.*;import android.graphics.*;import android.net.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;
public final class NearbyServicesActivity extends ComponentActivity{
    private LinearLayout page,results;private double lat=Double.NaN,lon=Double.NaN;private boolean reg;private BroadcastReceiver rx;private final int TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38);
    @Override protected void onCreate(Bundle b){super.onCreate(b);ScrollView sv=new ScrollView(this);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(18),dp(18),dp(18),dp(28));page.setBackgroundColor(Color.rgb(9,5,7));sv.addView(page);setContentView(sv);page.addView(t("SERVIÇOS NA ESTRADA",27,TEXT,true));page.addView(t("Busca online em até 15 km da posição atual. Não interfere na proteção offline.",12,MUTED,false));LinearLayout a=row();addButton(a,"POSTOS","fuel");addButton(a,"HOSPITAIS","hospital");page.addView(a);LinearLayout c=row();addButton(c,"OFICINAS","car_repair");addButton(c,"RESTAURANTES","restaurant");page.addView(c);results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);page.addView(results);}
    private void addButton(LinearLayout r,String label,String type){Button b=new Button(this);b.setText(label);b.setOnClickListener(v->search(type));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(52),1);p.setMargins(dp(3),dp(6),dp(3),0);r.addView(b,p);}
    private void search(String type){if(!Double.isFinite(lat)||!Double.isFinite(lon)){toast("Aguardando posição GPS.");return;}results.removeAllViews();results.addView(t("BUSCANDO...",14,RED,true));new Thread(()->{ArrayList<Item> items=query(type);runOnUiThread(()->show(items));},"epc-nearby").start();}
    private ArrayList<Item> query(String type){ArrayList<Item> out=new ArrayList<>();try{String selector;if("fuel".equals(type))selector="[\\\"amenity\\\"=\\\"fuel\\\"]";else if("hospital".equals(type))selector="[\\\"amenity\\\"=\\\"hospital\\\"]";else if("restaurant".equals(type))selector="[\\\"amenity\\\"=\\\"restaurant\\\"]";else selector="[\\\"shop\\\"=\\\"car_repair\\\"]";String q=String.format(Locale.US,"[out:json][timeout:25];(node(around:15000,%.6f,%.6f)%s;way(around:15000,%.6f,%.6f)%s;);out center tags 30;",lat,lon,selector,lat,lon,selector);URL u=new URL("https://overpass-api.de/api/interpreter?data="+URLEncoder.encode(q,"UTF-8"));HttpURLConnection h=(HttpURLConnection)u.openConnection();h.setConnectTimeout(12000);h.setReadTimeout(35000);h.setRequestProperty("User-Agent","EstradaPlayComunista/1.4 Android");try(InputStream in=h.getInputStream();ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[] buf=new byte[16384];int n;while((n=in.read(buf))>0&&b.size()<4000000)b.write(buf,0,n);JSONObject root=new JSONObject(new String(b.toByteArray(),StandardCharsets.UTF_8));JSONArray e=root.optJSONArray("elements");if(e!=null)for(int i=0;i<e.length();i++){JSONObject x=e.optJSONObject(i);if(x==null)continue;double la=x.optDouble("lat",Double.NaN),lo=x.optDouble("lon",Double.NaN);JSONObject center=x.optJSONObject("center");if(!Double.isFinite(la)&&center!=null){la=center.optDouble("lat",Double.NaN);lo=center.optDouble("lon",Double.NaN);}if(!Double.isFinite(la)||!Double.isFinite(lo))continue;JSONObject tags=x.optJSONObject("tags");String name=tags==null?"":tags.optString("name","");if(name.isEmpty())name=label(type);out.add(new Item(name,la,lo,distance(lat,lon,la,lo)));}}}out.sort(Comparator.comparingDouble(a->a.d));if(out.size()>15)return new ArrayList<>(out.subList(0,15));}catch(Throwable ignored){}return out;}
    private void show(ArrayList<Item> items){results.removeAllViews();if(items.isEmpty()){results.addView(t("Nenhum resultado encontrado agora.",14,MUTED,false));return;}for(Item x:items){Button b=new Button(this);b.setAllCaps(false);b.setText(x.name+"\n"+(x.d>=1000?String.format(Locale.getDefault(),"%.1f km",x.d/1000):Math.round(x.d)+" m"));b.setOnClickListener(v->{Uri u=Uri.parse("geo:"+x.lat+","+x.lon+"?q="+x.lat+","+x.lon+"("+Uri.encode(x.name)+")");try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Throwable e){toast("Nenhum app de mapas disponível.");}});results.addView(b,new LinearLayout.LayoutParams(-1,dp(68)));}}
    @Override protected void onStart(){super.onStart();rx=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){lat=i.getDoubleExtra("lat",Double.NaN);lon=i.getDoubleExtra("lon",Double.NaN);}};IntentFilter f=new IntentFilter(RoadSafetyService.ACTION_STATE);if(Build.VERSION.SDK_INT>=33)registerReceiver(rx,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(rx,f);reg=true;}
    @Override protected void onStop(){if(reg)try{unregisterReceiver(rx);}catch(Throwable ignored){}reg=false;super.onStop();}
    private String label(String t){if("fuel".equals(t))return"Posto";if("hospital".equals(t))return"Hospital";if("restaurant".equals(t))return"Restaurante";return"Oficina";}private static double distance(double a,double b,double c,double d){double R=6371000,p1=Math.toRadians(a),p2=Math.toRadians(c),dp=Math.toRadians(c-a),dl=Math.toRadians(d-b);double x=Math.sin(dp/2)*Math.sin(dp/2)+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)*Math.sin(dl/2);return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private TextView t(String v,float s,int c,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private void toast(String v){Toast.makeText(this,v,Toast.LENGTH_SHORT).show();}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}private static final class Item{final String name;final double lat,lon,d;Item(String n,double a,double b,double d){name=n;lat=a;lon=b;this.d=d;}}
}
''')

write('app/src/main/java/com/estradaplay/comunista/VoiceCommandActivity.java',r'''package com.estradaplay.comunista;
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.os.*;import android.speech.*;import android.speech.tts.TextToSpeech;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import java.util.*;
public final class VoiceCommandActivity extends ComponentActivity implements RecognitionListener{
    private static final int REQ=2201;private SpeechRecognizer sr;private TextToSpeech tts;private TextView state;private int lastLimit;private String lastHazard="";private double lastDistance;private boolean reg;private BroadcastReceiver rx;
    @Override protected void onCreate(Bundle b){super.onCreate(b);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setGravity(Gravity.CENTER);p.setPadding(dp(24),dp(24),dp(24),dp(24));p.setBackgroundColor(Color.rgb(9,5,7));setContentView(p);TextView title=t("COMANDO DE VOZ",28,Color.rgb(246,238,224),true);p.addView(title);TextView hint=t("Exemplos: ‘qual o limite’, ‘tem radar’, ‘abrir câmera’, ‘posto’, ‘histórico’, ‘HUD’, ‘reportar’, ‘definir destino’. O microfone só é usado enquanto esta tela escuta.",13,Color.rgb(174,151,146),false);hint.setGravity(Gravity.CENTER);p.addView(hint);state=t("TOQUE PARA FALAR",16,Color.rgb(224,184,76),true);state.setGravity(Gravity.CENTER);p.addView(state);Button speak=new Button(this);speak.setText("FALAR");speak.setOnClickListener(v->listen());p.addView(speak,new LinearLayout.LayoutParams(-1,dp(62)));tts=new TextToSpeech(this,x->{if(x==TextToSpeech.SUCCESS)tts.setLanguage(new Locale("pt","BR"));});}
    private void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ);return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){say("Reconhecimento de voz não está disponível neste aparelho.");return;}if(sr==null){sr=SpeechRecognizer.createSpeechRecognizer(this);sr.setRecognitionListener(this);}Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"pt-BR");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,3);state.setText("OUVINDO...");sr.startListening(i);}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)listen();}
    @Override public void onResults(Bundle b){ArrayList<String> a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);String q=a==null||a.isEmpty()?"":a.get(0).toLowerCase(Locale.ROOT);state.setText(q.isEmpty()?"NÃO ENTENDI":q.toUpperCase(Locale.ROOT));handle(q);}
    private void handle(String q){if(q.contains("limite")){say(lastLimit>0?"O limite registrado aqui é "+lastLimit+" quilômetros por hora.":"Ainda não tenho um limite confirmado para esta via.");return;}if(q.contains("radar")){say(lastHazard.toLowerCase(Locale.ROOT).contains("radar")?"Há radar detectado a aproximadamente "+Math.round(lastDistance)+" metros.":"Não há radar dentro da janela de alerta atual.");return;}if(q.contains("câmera")||q.contains("camera")){open(CameraActivity.class);return;}if(q.contains("posto")||q.contains("hospital")||q.contains("oficina")||q.contains("restaurante")){open(NearbyServicesActivity.class);return;}if(q.contains("histórico")||q.contains("historico")){open(TripHistoryActivity.class);return;}if(q.contains("hud")){open(HudActivity.class);return;}if(q.contains("report")){open(RoadReportActivity.class);return;}if(q.contains("destino")||q.contains("endereço")||q.contains("endereco")){open(DestinationActivity.class);return;}say("Comando não reconhecido ainda.");}
    private void open(Class<?> c){startActivity(new Intent(this,c));}
    private void say(String v){state.setText(v);try{if(tts!=null)tts.speak(v,TextToSpeech.QUEUE_FLUSH,null,"epc-command");}catch(Throwable ignored){}}
    @Override protected void onStart(){super.onStart();rx=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){lastLimit=i.getIntExtra("road_limit_kmh",0);String h=i.getStringExtra("hazard_label");if(h!=null&&!h.isEmpty()){lastHazard=h;lastDistance=i.getDoubleExtra("distance_m",0);}}};IntentFilter f=new IntentFilter(RoadSafetyService.ACTION_STATE);if(Build.VERSION.SDK_INT>=33)registerReceiver(rx,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(rx,f);reg=true;}
    @Override protected void onStop(){if(reg)try{unregisterReceiver(rx);}catch(Throwable ignored){}reg=false;super.onStop();}
    @Override protected void onDestroy(){try{if(sr!=null)sr.destroy();}catch(Throwable ignored){}try{if(tts!=null){tts.stop();tts.shutdown();}}catch(Throwable ignored){}super.onDestroy();}
    @Override public void onReadyForSpeech(Bundle p){}@Override public void onBeginningOfSpeech(){}@Override public void onRmsChanged(float r){}@Override public void onBufferReceived(byte[] b){}@Override public void onEndOfSpeech(){}@Override public void onError(int e){state.setText("TOQUE PARA TENTAR NOVAMENTE");}@Override public void onPartialResults(Bundle b){}@Override public void onEvent(int e,Bundle b){}
    private TextView t(String v,float s,int c,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
''')

tools=read('app/src/main/java/com/estradaplay/comunista/DriveToolsActivity.java')
tools=rep(tools,'button("CÂMERA / DASHCAM",CameraActivity.class);','button("CÂMERA / DASHCAM",CameraActivity.class);button("SERVIÇOS PRÓXIMOS",NearbyServicesActivity.class);button("COMANDO DE VOZ",VoiceCommandActivity.class);','tools extras')
write('app/src/main/java/com/estradaplay/comunista/DriveToolsActivity.java',tools)
print('Estrada Play Comunista 1.4.0 nearby services + voice commands patched')
