#!/usr/bin/env python3
from pathlib import Path
ROOT=Path('estrada-play-comunista-app');J=ROOT/'app/src/main/java/com/estradaplay/comunista'
def read(p):return p.read_text(encoding='utf-8')
def write(p,s):p.write_text(s,encoding='utf-8')
def rep(s,old,new,label):
    if old not in s:raise SystemExit('missing anchor: '+label)
    return s.replace(old,new,1)

write(J/'VehicleCostActivity.java',r'''package com.estradaplay.comunista;
import android.graphics.*;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import java.util.Locale;
public final class VehicleCostActivity extends ComponentActivity{
 private final int BG=Color.rgb(9,5,7),TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38);
 @Override protected void onCreate(Bundle b){super.onCreate(b);build();}
 private void build(){ScrollView sv=new ScrollView(this);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(20),dp(20),dp(20),dp(30));p.setBackgroundColor(BG);sv.addView(p);setContentView(sv);p.addView(t("CUSTO DA VIAGEM",27,TEXT,true));p.addView(t("Estimativa local de combustível. Pedágios só entram quando houver fonte confiável.",12,MUTED,false));EditText km=new EditText(this);km.setHint("Consumo km/l");km.setText(String.format(Locale.US,"%.1f",DriveSettings.consumptionKml(this)));km.setTextColor(TEXT);km.setHintTextColor(MUTED);km.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);p.addView(km,new LinearLayout.LayoutParams(-1,dp(56)));EditText price=new EditText(this);price.setHint("Preço combustível R$/l");price.setText(String.format(Locale.US,"%.2f",DriveSettings.fuelPrice(this)));price.setTextColor(TEXT);price.setHintTextColor(MUTED);price.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);p.addView(price,new LinearLayout.LayoutParams(-1,dp(56)));Button save=new Button(this);save.setText("SALVAR PERFIL");save.setTextColor(TEXT);save.setBackgroundColor(RED);p.addView(save,new LinearLayout.LayoutParams(-1,dp(56)));save.setOnClickListener(v->{try{float a=Float.parseFloat(km.getText().toString().replace(',','.'));float f=Float.parseFloat(price.getText().toString().replace(',','.'));DriveSettings.setVehicleCost(this,a,f);Toast.makeText(this,"Perfil salvo",Toast.LENGTH_SHORT).show();}catch(Throwable e){Toast.makeText(this,"Confira os valores",Toast.LENGTH_SHORT).show();}});}
 private TextView t(String v,float s,int c,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
''')

write(J/'OfflineCenterActivity.java',r'''package com.estradaplay.comunista;
import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import java.text.*;import java.util.*;
public final class OfflineCenterActivity extends ComponentActivity{
 private final int BG=Color.rgb(9,5,7),TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38),GREEN=Color.rgb(69,212,131);private LinearLayout page;
 @Override protected void onCreate(Bundle b){super.onCreate(b);build();}
 @Override protected void onResume(){super.onResume();if(page!=null)build();}
 private void build(){ScrollView sv=new ScrollView(this);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(18),dp(18),dp(18),dp(30));page.setBackgroundColor(BG);sv.addView(page);setContentView(sv);RoadPackStore s=new RoadPackStore(this);page.addView(t("CENTRAL OFFLINE",27,TEXT,true));page.addView(t("Antes de viajar sem sinal, confira os três estados.",12,MUTED,false));for(String uf:new String[]{"RJ","MG","ES"}){int n=s.stateHazardCount(uf);long at=s.stateFetchedAt(uf);String date=at>0?new SimpleDateFormat("dd/MM HH:mm",Locale.getDefault()).format(new Date(at)):"não baixado";TextView row=t(uf+"  "+(n>0?"✓":"…")+"   "+n+" pontos\nÚltima base: "+date,16,n>0?GREEN:TEXT,true);row.setPadding(dp(12),dp(14),dp(12),dp(14));page.addView(row,new LinearLayout.LayoutParams(-1,-2));}page.addView(t("Total local: "+s.hazardCount()+" pontos · "+s.coreStatesStatus(),13,MUTED,false));Button check=new Button(this);check.setText("PREPARAR / VERIFICAR RJ + MG + ES");check.setTextColor(TEXT);check.setBackgroundColor(RED);page.addView(check,new LinearLayout.LayoutParams(-1,dp(58)));check.setOnClickListener(v->{Intent i=new Intent(this,RoadSafetyService.class).setAction(RoadSafetyService.ACTION_PREFETCH_CORE);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);Toast.makeText(this,"Verificação iniciada. Mantenha internet por alguns minutos.",Toast.LENGTH_LONG).show();});}
 private TextView t(String v,float s,int c,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
''')

write(J/'CollectiveRoadActivity.java',r'''package com.estradaplay.comunista;
import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import org.json.*;import java.text.*;import java.util.*;
public final class CollectiveRoadActivity extends ComponentActivity{
 private final int BG=Color.rgb(9,5,7),TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38),GREEN=Color.rgb(69,212,131),BORDER=Color.rgb(76,38,43);private LinearLayout page;private CollectiveRoadStore store;
 @Override protected void onCreate(Bundle b){super.onCreate(b);store=new CollectiveRoadStore(this);build();}
 private void build(){ScrollView sv=new ScrollView(this);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(18),dp(18),dp(18),dp(30));page.setBackgroundColor(BG);sv.addView(page);setContentView(sv);page.addView(t("INTELIGÊNCIA COLETIVA",27,TEXT,true));page.addView(t("O aparelho detecta irregularidades pelos sensores. Só pequenos eventos e coordenadas podem ir ao servidor; vídeos nunca são enviados.",12,MUTED,false));CheckBox on=new CheckBox(this);on.setText("PARTICIPAR DA BASE COLETIVA");on.setTextColor(TEXT);on.setChecked(DriveSettings.collectiveEnabled(this));on.setOnCheckedChangeListener((b,v)->DriveSettings.toggle(this,"collective_enabled",v));page.addView(on);CheckBox protect=new CheckBox(this);protect.setText("PROTEGER VÍDEO DA DASHCAM EM IMPACTO\nFunciona apenas quando a câmera/dashcam estiver aberta e gravando.");protect.setTextColor(TEXT);protect.setChecked(DriveSettings.protectImpactVideo(this));protect.setOnCheckedChangeListener((b,v)->DriveSettings.toggle(this,"protect_impact_video",v));page.addView(protect);page.addView(t("Impactos detectados neste aparelho: "+store.impactCount()+" · fila para sincronizar: "+store.queuedCount(),13,GREEN,true));TextView h=t("RADARES PARA CONFIRMAR DEPOIS",15,RED,true);page.addView(h);JSONArray a=store.pending();if(a.length()==0)page.addView(t("Nenhum radar pendente. Quando um radar for alertado, ele entra aqui para você confirmar quando estiver seguro.",12,MUTED,false));for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String id=o.optString("radar_id");LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(12),dp(12),dp(12));c.setBackground(box(Color.rgb(22,10,13),10,BORDER));String road=o.optString("road","Radar");int lim=o.optInt("limit_kmh",0);c.addView(t(road+(lim>0?" · "+lim+" km/h":""),15,TEXT,true));long at=o.optLong("seen_at");if(at>0)c.addView(t(new SimpleDateFormat("dd/MM HH:mm",Locale.getDefault()).format(new Date(at))+" · "+o.optString("source",""),10,MUTED,false));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);Button yes=b("AINDA EXISTE",GREEN);Button no=b("NÃO ESTÁ MAIS",RED);r.addView(yes,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(0,dp(48),1);np.setMargins(dp(6),0,0,0);r.addView(no,np);c.addView(r);yes.setOnClickListener(v->{store.resolveRadar(id,"exists");build();});no.setOnClickListener(v->{store.resolveRadar(id,"removed");build();});page.addView(c);}}
 private Button b(String s,int c){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setBackgroundColor(c);return b;}private TextView t(String v,float s,int c,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable box(int c,int r,int st){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));d.setStroke(dp(1),st);return d;}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
''')

# Drive tools gets direct access to new features.
write(J/'DriveToolsActivity.java',r'''package com.estradaplay.comunista;
import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;
public final class DriveToolsActivity extends ComponentActivity{
 private LinearLayout page;private int TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38);
 @Override protected void onCreate(Bundle b){super.onCreate(b);build();}
 private void build(){ScrollView s=new ScrollView(this);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(20),dp(20),dp(20),dp(30));page.setBackgroundColor(Color.rgb(9,5,7));s.addView(page);setContentView(s);page.addView(t("CENTRAL INTELIGENTE",27,TEXT,true));page.addView(t("Preferências locais, offline e inteligência coletiva",12,MUTED,false));check("MODO NOTURNO AUTOMÁTICO","Escurece instrumentos à noite.","auto_night",DriveSettings.autoNight(this));check("HUD ESPELHADO","Inverte o HUD para refletir no para-brisa.","hud_mirror",DriveSettings.hudMirror(this));check("BASE COLETIVA","Envia somente pequenos eventos de via; nunca vídeo.","collective_enabled",DriveSettings.collectiveEnabled(this));check("PROTEGER VÍDEO EM IMPACTO","Preserva o trecho quando a dashcam estiver aberta.","protect_impact_video",DriveSettings.protectImpactVideo(this));button("CENTRAL OFFLINE RJ / MG / ES",OfflineCenterActivity.class);button("INTELIGÊNCIA COLETIVA / RADARES",CollectiveRoadActivity.class);button("CUSTO / PERFIL DO VEÍCULO",VehicleCostActivity.class);button("ABRIR HUD",HudActivity.class);button("HISTÓRICO E LINHA DO TEMPO",TripHistoryActivity.class);button("REPORTAR PONTO DA VIA",RoadReportActivity.class);button("CÂMERA / DASHCAM",CameraActivity.class);button("SERVIÇOS PRÓXIMOS",NearbyServicesActivity.class);button("COMANDO DE VOZ",VoiceCommandActivity.class);}
 private void check(String title,String sub,String key,boolean initial){CheckBox c=new CheckBox(this);c.setText(title+"\n"+sub);c.setTextColor(TEXT);c.setTextSize(14);c.setChecked(initial);c.setPadding(0,dp(10),0,dp(10));c.setOnCheckedChangeListener((b,v)->DriveSettings.toggle(this,key,v));page.addView(c,new LinearLayout.LayoutParams(-1,-2));}
 private void button(String label,Class<?> cls){Button b=new Button(this);b.setText(label);b.setTextColor(TEXT);b.setBackgroundColor(Color.rgb(62,14,23));b.setOnClickListener(v->startActivity(new Intent(this,cls)));page.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));}
 private TextView t(String v,float s,int c,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
''')

# History now surfaces road quality, estimated fuel and event timeline.
write(J/'TripHistoryActivity.java',r'''package com.estradaplay.comunista;
import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import androidx.activity.ComponentActivity;import org.json.*;import java.text.*;import java.util.*;
public final class TripHistoryActivity extends ComponentActivity{
 private final int BG=Color.rgb(9,5,7),TEXT=Color.rgb(246,238,224),MUTED=Color.rgb(174,151,146),RED=Color.rgb(190,18,38),BORDER=Color.rgb(76,38,43),GREEN=Color.rgb(69,212,131);
 @Override protected void onCreate(Bundle b){super.onCreate(b);showHistory();}
 private void showHistory(){ScrollView sv=new ScrollView(this);LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(18),dp(18),dp(18),dp(30));page.setBackgroundColor(BG);sv.addView(page);setContentView(sv);page.addView(t("HISTÓRICO + LINHA DO TEMPO",26,TEXT,true));page.addView(t("Dados ficam neste aparelho. Eventos coletivos são enviados separadamente e sem vídeo.",12,MUTED,false));JSONArray a=TripRecorder.history(this);if(a.length()==0){TextView empty=t("Nenhuma viagem registrada ainda.",15,MUTED,false);page.addView(empty);m(empty,0,30,0,0);}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(13),dp(14),dp(13));c.setBackground(box(Color.rgb(22,10,13),12,BORDER));long start=o.optLong("started_at");double km=o.optDouble("distance_m")/1000.0;long dur=o.optLong("duration_ms");String date=new SimpleDateFormat("dd/MM/yyyy HH:mm",Locale.getDefault()).format(new Date(start));c.addView(t(date,13,RED,true));c.addView(t(String.format(Locale.getDefault(),"%.1f km · %s · máxima %.0f km/h",km,duration(dur),o.optDouble("max_speed")),16,TEXT,true));c.addView(t("Radares "+o.optInt("radars")+" · Quebra-molas "+o.optInt("bumps")+" · Câmeras "+o.optInt("cameras")+" · Impactos "+o.optInt("road_impacts"),11,MUTED,false));int q=o.optInt("road_quality_score",100);c.addView(t("QUALIDADE ESTIMADA DA VIA · "+q+"/100",12,q>=75?GREEN:(q>=50?Color.rgb(226,185,76):RED),true));double fuel=o.optDouble("fuel_l",0),cost=o.optDouble("fuel_cost",0);if(fuel>0)c.addView(t(String.format(Locale.getDefault(),"Combustível estimado %.1f L%s",fuel,cost>0?" · R$ %.2f":"",cost),11,MUTED,false));JSONArray tl=o.optJSONArray("timeline");if(tl!=null&&tl.length()>0){c.addView(t("LINHA DO TEMPO",10,RED,true));for(int x=0;x<tl.length();x++){JSONObject e=tl.optJSONObject(x);if(e==null)continue;String tm=new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(e.optLong("at")));c.addView(t(tm+" · "+e.optString("label",e.optString("type")),10,MUTED,false));}}page.addView(c);m(c,0,10,0,0);}Button clear=new Button(this);clear.setText("LIMPAR HISTÓRICO");clear.setOnClickListener(v->{TripRecorder.clear(this);showHistory();});page.addView(clear,new LinearLayout.LayoutParams(-1,dp(50)));m(clear,0,18,0,0);}
 private String duration(long ms){long min=Math.max(0,ms/60000);return (min/60)+"h "+(min%60)+"min";}private TextView t(String v,float s,int c,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable box(int c,int r,int st){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));d.setStroke(dp(1),st);return d;}private void m(View v,int l,int t,int r,int b){if(v.getLayoutParams() instanceof LinearLayout.LayoutParams){LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)v.getLayoutParams();p.setMargins(dp(l),dp(t),dp(r),dp(b));v.setLayoutParams(p);}}private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
''')

# Manifest registrations.
p=ROOT/'app/src/main/AndroidManifest.xml';s=read(p)
anchor='''        <activity\n            android:name=".DriveToolsActivity"\n            android:exported="false"\n            android:screenOrientation="${appOrientation}" />'''
new=anchor+'''\n\n        <activity android:name=".OfflineCenterActivity" android:exported="false" android:screenOrientation="${appOrientation}" />\n        <activity android:name=".CollectiveRoadActivity" android:exported="false" android:screenOrientation="${appOrientation}" />\n        <activity android:name=".VehicleCostActivity" android:exported="false" android:screenOrientation="${appOrientation}" />'''
s=rep(s,anchor,new,'manifest activities');write(p,s)
print('patched collective UI v1.5.0')
