<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
require_once __DIR__.'/native_auth.php';
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
$body=input_json();$user=native_require_json_user($body);$pdo=db();$driver=(string)$pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

function radio_schema(PDO $pdo,string $driver):void{
 if($driver==='mysql'){
  $pdo->exec("CREATE TABLE IF NOT EXISTS radio_presence (device_token VARCHAR(128) PRIMARY KEY,user_id BIGINT NULL,room_key VARCHAR(190) NOT NULL,road VARCHAR(32) NOT NULL,direction VARCHAR(16) NOT NULL,segment VARCHAR(40) NOT NULL,nickname VARCHAR(40) NOT NULL,joined_at DATETIME NOT NULL,last_seen_at DATETIME NOT NULL,KEY idx_radio_room_seen(room_key,last_seen_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  $pdo->exec("CREATE TABLE IF NOT EXISTS radio_signals (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,room_key VARCHAR(190) NOT NULL,from_device VARCHAR(128) NOT NULL,to_device VARCHAR(128) NOT NULL,signal_type VARCHAR(12) NOT NULL,payload MEDIUMTEXT NOT NULL,created_at DATETIME NOT NULL,KEY idx_radio_signal_to(to_device,id),KEY idx_radio_signal_room(room_key,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  $pdo->exec("CREATE TABLE IF NOT EXISTS radio_alerts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,room_key VARCHAR(190) NOT NULL,device_token VARCHAR(128) NOT NULL,alert_type VARCHAR(24) NOT NULL,created_at DATETIME NOT NULL,expires_at DATETIME NOT NULL,KEY idx_radio_alert_room(room_key,expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 }else{
  $pdo->exec("CREATE TABLE IF NOT EXISTS radio_presence (device_token TEXT PRIMARY KEY,user_id INTEGER,room_key TEXT NOT NULL,road TEXT NOT NULL,direction TEXT NOT NULL,segment TEXT NOT NULL,nickname TEXT NOT NULL,joined_at TEXT NOT NULL,last_seen_at TEXT NOT NULL)");
  $pdo->exec("CREATE TABLE IF NOT EXISTS radio_signals (id INTEGER PRIMARY KEY AUTOINCREMENT,room_key TEXT NOT NULL,from_device TEXT NOT NULL,to_device TEXT NOT NULL,signal_type TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL)");
  $pdo->exec("CREATE TABLE IF NOT EXISTS radio_alerts (id INTEGER PRIMARY KEY AUTOINCREMENT,room_key TEXT NOT NULL,device_token TEXT NOT NULL,alert_type TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL)");
 }
}
function radio_clean(PDO $pdo):void{try{$pdo->prepare('DELETE FROM radio_presence WHERE last_seen_at < ?')->execute([date('Y-m-d H:i:s',time()-20)]);$pdo->prepare('DELETE FROM radio_signals WHERE created_at < ?')->execute([date('Y-m-d H:i:s',time()-120)]);$pdo->prepare('DELETE FROM radio_alerts WHERE expires_at < ?')->execute([date('Y-m-d H:i:s')]);}catch(Throwable $e){}}
function radio_room(array $b):array{$room=strtoupper(trim((string)($b['room_key']??'')));$road=strtoupper(trim((string)($b['road']??'')));$dir=strtoupper(trim((string)($b['direction']??'')));$seg=trim((string)($b['segment']??''));if(!preg_match('/^[A-Z0-9|_-]{5,190}$/',$room)||!preg_match('/^(BR|RJ|MG|ES|SP)-[0-9]{1,4}$/',$road))json_response(['ok'=>false,'error'=>'Rodovia ainda não reconhecida.'],422);return[$room,$road,substr($dir,0,16),substr($seg,0,40)];}
function radio_peers(PDO $pdo,string $room,string $self):array{$q=$pdo->prepare('SELECT device_token FROM radio_presence WHERE room_key=? AND last_seen_at>=? AND device_token<>? ORDER BY last_seen_at DESC LIMIT 7');$q->execute([$room,date('Y-m-d H:i:s',time()-20),$self]);return array_values(array_map(fn($r)=>(string)$r['device_token'],$q->fetchAll()?:[]));}
function radio_alert_rows(PDO $pdo,string $room):array{$q=$pdo->prepare('SELECT alert_type,created_at FROM radio_alerts WHERE room_key=? AND expires_at>=? ORDER BY id DESC LIMIT 8');$q->execute([$room,date('Y-m-d H:i:s')]);$out=[];foreach($q->fetchAll()?:[] as $r)$out[]=['type'=>(string)$r['alert_type'],'at'=>strtotime((string)$r['created_at'])];return$out;}
function radio_ice():array{$out=[['url'=>'stun:stun.l.google.com:19302']];$url=trim((string)app_setting('radio_turn_url',''));if($url!=='')$out[]=['url'=>$url,'username'=>(string)app_setting('radio_turn_username',''),'password'=>(string)app_setting('radio_turn_password','')];return$out;}
radio_schema($pdo,$driver);radio_clean($pdo);if(app_setting('radio_enabled','1')==='0')json_response(['ok'=>false,'error'=>'Rádio temporariamente desativado pelo servidor.'],503);
$device=native_device_token_from_request($body);if($device==='')json_response(['ok'=>false,'error'=>'Dispositivo inválido.'],401);$action=strtolower(trim((string)($_GET['action']??'')));
if($action==='leave'){try{$pdo->prepare('DELETE FROM radio_presence WHERE device_token=?')->execute([$device]);}catch(Throwable $e){}json_response(['ok'=>true]);}
[$room,$road,$direction,$segment]=radio_room($body);$nickname=substr(preg_replace('/[^A-Z0-9_-]/i','',strtoupper((string)($body['nickname']??'MOTORISTA'))),0,40);if($nickname==='')$nickname='MOTORISTA';$now=date('Y-m-d H:i:s');
if($action==='join'){
 $q=$pdo->prepare('SELECT COUNT(*) FROM radio_presence WHERE room_key=? AND last_seen_at>=? AND device_token<>?');$q->execute([$room,date('Y-m-d H:i:s',time()-20),$device]);if((int)$q->fetchColumn()>=7)json_response(['ok'=>false,'error'=>'Este trecho já atingiu 8 participantes. Avance alguns quilômetros ou tente novamente.'],409);
 try{if($driver==='mysql'){$q=$pdo->prepare("INSERT INTO radio_presence(device_token,user_id,room_key,road,direction,segment,nickname,joined_at,last_seen_at) VALUES(?,?,?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE user_id=VALUES(user_id),room_key=VALUES(room_key),road=VALUES(road),direction=VALUES(direction),segment=VALUES(segment),nickname=VALUES(nickname),last_seen_at=NOW()");$q->execute([$device,(int)$user['id'],$room,$road,$direction,$segment,$nickname]);}else{$pdo->prepare('DELETE FROM radio_presence WHERE device_token=?')->execute([$device]);$pdo->prepare('INSERT INTO radio_presence(device_token,user_id,room_key,road,direction,segment,nickname,joined_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$device,(int)$user['id'],$room,$road,$direction,$segment,$nickname,$now,$now]);}}catch(Throwable $e){error_log('RADIO_JOIN '.$e->getMessage());json_response(['ok'=>false,'error'=>'Não foi possível entrar no rádio.'],503);}json_response(['ok'=>true,'self'=>$device,'room'=>['key'=>$room,'road'=>$road,'direction'=>$direction,'segment'=>$segment],'peers'=>radio_peers($pdo,$room,$device),'alerts'=>radio_alert_rows($pdo,$room),'ice_servers'=>radio_ice(),'max_participants'=>8,'audio_stored'=>false]);
}
// Heartbeats also keep room membership fresh; device must already be joined to the same room.
$q=$pdo->prepare('SELECT room_key FROM radio_presence WHERE device_token=? LIMIT 1');$q->execute([$device]);$current=(string)($q->fetchColumn()?:'');if($current!==$room)json_response(['ok'=>false,'error'=>'Entre novamente na sala.'],409);$pdo->prepare('UPDATE radio_presence SET last_seen_at=? WHERE device_token=?')->execute([$now,$device]);
if($action==='signal'){$to=strtolower(trim((string)($body['to']??'')));$type=strtolower(trim((string)($body['signal_type']??'')));$payload=$body['payload']??null;if(!preg_match('/^[a-f0-9]{32,128}$/',$to)||!in_array($type,['offer','answer','ice'],true)||!is_array($payload))json_response(['ok'=>false,'error'=>'Sinal inválido.'],422);$check=$pdo->prepare('SELECT COUNT(*) FROM radio_presence WHERE device_token=? AND room_key=? AND last_seen_at>=?');$check->execute([$to,$room,date('Y-m-d H:i:s',time()-20)]);if((int)$check->fetchColumn()!==1)json_response(['ok'=>false,'error'=>'Motorista não está mais no trecho.'],410);$raw=json_encode($payload,JSON_UNESCAPED_SLASHES);if($raw===false||strlen($raw)>24000)json_response(['ok'=>false,'error'=>'Sinal muito grande.'],422);$rate=$pdo->prepare('SELECT COUNT(*) FROM radio_signals WHERE from_device=? AND created_at>=?');$rate->execute([$device,date('Y-m-d H:i:s',time()-60)]);if((int)$rate->fetchColumn()>160)json_response(['ok'=>false,'error'=>'Muitas tentativas de conexão. Aguarde alguns segundos.'],429);$pdo->prepare('INSERT INTO radio_signals(room_key,from_device,to_device,signal_type,payload,created_at) VALUES(?,?,?,?,?,?)')->execute([$room,$device,$to,$type,$raw,$now]);json_response(['ok'=>true]);}
if($action==='alert'){$type=strtoupper(trim((string)($body['alert_type']??'')));if(!in_array($type,['ACIDENTE','OBJETO','OBRA','TRANSITO','CHUVA'],true))json_response(['ok'=>false,'error'=>'Alerta inválido.'],422);$q=$pdo->prepare('SELECT COUNT(*) FROM radio_alerts WHERE room_key=? AND device_token=? AND alert_type=? AND created_at>=?');$q->execute([$room,$device,$type,date('Y-m-d H:i:s',time()-120)]);if((int)$q->fetchColumn()>0)json_response(['ok'=>true,'duplicate'=>true]);$pdo->prepare('INSERT INTO radio_alerts(room_key,device_token,alert_type,created_at,expires_at) VALUES(?,?,?,?,?)')->execute([$room,$device,$type,$now,date('Y-m-d H:i:s',time()+1800)]);json_response(['ok'=>true,'stored'=>true]);}
if($action==='heartbeat'){$since=max(0,(int)($body['since_signal_id']??0));$q=$pdo->prepare('SELECT id,from_device,signal_type,payload FROM radio_signals WHERE to_device=? AND room_key=? AND id>? ORDER BY id ASC LIMIT 120');$q->execute([$device,$room,$since]);$signals=[];foreach($q->fetchAll()?:[] as $r){$p=json_decode((string)$r['payload'],true);$signals[]=['id'=>(int)$r['id'],'from'=>(string)$r['from_device'],'type'=>(string)$r['signal_type'],'payload'=>is_array($p)?$p:[]];}json_response(['ok'=>true,'peers'=>radio_peers($pdo,$room,$device),'signals'=>$signals,'alerts'=>radio_alert_rows($pdo,$room),'audio_stored'=>false]);}
json_response(['ok'=>false,'error'=>'Ação inválida.'],404);
